---
title: "Plots for accuracy measures for setting 1"
author: "Reetika Sarkar"
output: html_document
---

```{r load_libraries}
## SETTING 1: p = 0.1, 0.3, 0.5
#plots for accuracy measures

library(ggplot2)
library(gridExtra)
library(ggpubr)
```

```{r read_results_data}
#read file from drive
# for p = 0.1
results_loc_p_0_1_beta1 <- "/Users/reetikasarkar/Documents/dissertation_research/apriori_project/codes/results/naive_setting_1d_3ae/p_0_1/beta_1"
results_loc_p_0_1_beta10 <- "/Users/reetikasarkar/Documents/dissertation_research/apriori_project/codes/results/naive_setting_1d_3ae/p_0_1/beta_10"
results_loc_p_0_1_beta50 <- "/Users/reetikasarkar/Documents/dissertation_research/apriori_project/codes/results/naive_setting_1d_3ae/p_0_1/beta_50"
results_loc_p_0_1_beta100 <- "/Users/reetikasarkar/Documents/dissertation_research/apriori_project/codes/results/naive_setting_1d_3ae/p_0_1/beta_100"

# for p = 0.3
results_loc_p_0_3_beta1 <- "/Users/reetikasarkar/Documents/dissertation_research/apriori_project/codes/results/naive_setting_1d_3ae/p_0_3/beta_1"
results_loc_p_0_3_beta10 <- "/Users/reetikasarkar/Documents/dissertation_research/apriori_project/codes/results/naive_setting_1d_3ae/p_0_3/beta_10"
results_loc_p_0_3_beta50 <- "/Users/reetikasarkar/Documents/dissertation_research/apriori_project/codes/results/naive_setting_1d_3ae/p_0_3/beta_50"
results_loc_p_0_3_beta100 <- "/Users/reetikasarkar/Documents/dissertation_research/apriori_project/codes/results/naive_setting_1d_3ae/p_0_3/beta_100"

# for p = 0.5
results_loc_p_0_5_beta1 <- "/Users/reetikasarkar/Documents/dissertation_research/apriori_project/codes/results/naive_setting_1d_3ae/p_0_5/beta_1"
results_loc_p_0_5_beta10 <- "/Users/reetikasarkar/Documents/dissertation_research/apriori_project/codes/results/naive_setting_1d_3ae/p_0_5/beta_10"
results_loc_p_0_5_beta50 <- "/Users/reetikasarkar/Documents/dissertation_research/apriori_project/codes/results/naive_setting_1d_3ae/p_0_5/beta_50"
results_loc_p_0_5_beta100 <- "/Users/reetikasarkar/Documents/dissertation_research/apriori_project/codes/results/naive_setting_1d_3ae/p_0_5/beta_100"
```

```{r read_conf_values}
#read conf values for each beta 
# for p = 0.1
conf_results_p_0_1_beta1 <- read.table(paste0(results_loc_p_0_1_beta1,"/conf.csv"), header = T)
conf_results_p_0_1_beta10 <- read.table(paste0(results_loc_p_0_1_beta10,"/conf.csv"), header = T)
conf_results_p_0_1_beta50 <- read.table(paste0(results_loc_p_0_1_beta50,"/conf.csv"), header = T)
conf_results_p_0_1_beta100 <- read.table(paste0(results_loc_p_0_1_beta100,"/conf.csv"), header = T)

# for p = 0.3
conf_results_p_0_3_beta1 <- read.table(paste0(results_loc_p_0_3_beta1,"/conf.csv"), header = T)
conf_results_p_0_3_beta10 <- read.table(paste0(results_loc_p_0_3_beta10,"/conf.csv"), header = T)
conf_results_p_0_3_beta50 <- read.table(paste0(results_loc_p_0_3_beta50,"/conf.csv"), header = T)
conf_results_p_0_3_beta100 <- read.table(paste0(results_loc_p_0_3_beta100,"/conf.csv"), header = T)

# for p = 0.5
conf_results_p_0_5_beta1 <- read.table(paste0(results_loc_p_0_5_beta1,"/conf.csv"), header = T)
conf_results_p_0_5_beta10 <- read.table(paste0(results_loc_p_0_5_beta10,"/conf.csv"), header = T)
conf_results_p_0_5_beta50 <- read.table(paste0(results_loc_p_0_5_beta50,"/conf.csv"), header = T)
conf_results_p_0_5_beta100 <- read.table(paste0(results_loc_p_0_5_beta100,"/conf.csv"), header = T)
```

```{r read_prr_values}
#read prr values for each beta
# for p = 0.1
prr_results_p_0_1_beta1 <- read.table(paste0(results_loc_p_0_1_beta1,"/prr.csv"), header = T)
prr_results_p_0_1_beta10 <- read.table(paste0(results_loc_p_0_1_beta10,"/prr.csv"), header = T)
prr_results_p_0_1_beta50 <- read.table(paste0(results_loc_p_0_1_beta50,"/prr.csv"), header = T)
prr_results_p_0_1_beta100 <- read.table(paste0(results_loc_p_0_1_beta100,"/prr.csv"), header = T)

# for p = 0.3
prr_results_p_0_3_beta1 <- read.table(paste0(results_loc_p_0_3_beta1,"/prr.csv"), header = T)
prr_results_p_0_3_beta10 <- read.table(paste0(results_loc_p_0_3_beta10,"/prr.csv"), header = T)
prr_results_p_0_3_beta50 <- read.table(paste0(results_loc_p_0_3_beta50,"/prr.csv"), header = T)
prr_results_p_0_3_beta100 <- read.table(paste0(results_loc_p_0_3_beta100,"/prr.csv"), header = T)

# for p = 0.5
prr_results_p_0_5_beta1 <- read.table(paste0(results_loc_p_0_5_beta1,"/prr.csv"), header = T)
prr_results_p_0_5_beta10 <- read.table(paste0(results_loc_p_0_5_beta10,"/prr.csv"), header = T)
prr_results_p_0_5_beta50 <- read.table(paste0(results_loc_p_0_5_beta50,"/prr.csv"), header = T)
prr_results_p_0_5_beta100 <- read.table(paste0(results_loc_p_0_5_beta100,"/prr.csv"), header = T)
```

```{r read_rr_values}
#read rr values for each beta
# for p = 0.1
rr_results_p_0_1_beta1 <- read.table(paste0(results_loc_p_0_1_beta1,"/rr.csv"), header = T)
rr_results_p_0_1_beta10 <- read.table(paste0(results_loc_p_0_1_beta10,"/rr.csv"), header = T)
rr_results_p_0_1_beta50 <- read.table(paste0(results_loc_p_0_1_beta50,"/rr.csv"), header = T)
rr_results_p_0_1_beta100 <- read.table(paste0(results_loc_p_0_1_beta100,"/rr.csv"), header = T)

# for p = 0.3
rr_results_p_0_3_beta1 <- read.table(paste0(results_loc_p_0_3_beta1,"/rr.csv"), header = T)
rr_results_p_0_3_beta10 <- read.table(paste0(results_loc_p_0_3_beta10,"/rr.csv"), header = T)
rr_results_p_0_3_beta50 <- read.table(paste0(results_loc_p_0_3_beta50,"/rr.csv"), header = T)
rr_results_p_0_3_beta100 <- read.table(paste0(results_loc_p_0_3_beta100,"/rr.csv"), header = T)

# for p = 0.5
rr_results_p_0_5_beta1 <- read.table(paste0(results_loc_p_0_5_beta1,"/rr.csv"), header = T)
rr_results_p_0_5_beta10 <- read.table(paste0(results_loc_p_0_5_beta10,"/rr.csv"), header = T)
rr_results_p_0_5_beta50 <- read.table(paste0(results_loc_p_0_5_beta50,"/rr.csv"), header = T)
rr_results_p_0_5_beta100 <- read.table(paste0(results_loc_p_0_5_beta100,"/rr.csv"), header = T)
```

```{r read_ror_values}
#read ror values for each beta
# for p = 0.1
ror_results_p_0_1_beta1 <- read.table(paste0(results_loc_p_0_1_beta1,"/ror.csv"), header = T)
ror_results_p_0_1_beta10 <- read.table(paste0(results_loc_p_0_1_beta10,"/ror.csv"), header = T)
ror_results_p_0_1_beta50 <- read.table(paste0(results_loc_p_0_1_beta50,"/ror.csv"), header = T)
ror_results_p_0_1_beta100 <- read.table(paste0(results_loc_p_0_1_beta100,"/ror.csv"), header = T)

# for p = 0.3
ror_results_p_0_3_beta1 <- read.table(paste0(results_loc_p_0_3_beta1,"/ror.csv"), header = T)
ror_results_p_0_3_beta10 <- read.table(paste0(results_loc_p_0_3_beta10,"/ror.csv"), header = T)
ror_results_p_0_3_beta50 <- read.table(paste0(results_loc_p_0_3_beta50,"/ror.csv"), header = T)
ror_results_p_0_3_beta100 <- read.table(paste0(results_loc_p_0_3_beta100,"/ror.csv"), header = T)

# for p = 0.5
ror_results_p_0_5_beta1 <- read.table(paste0(results_loc_p_0_5_beta1,"/ror.csv"), header = T)
ror_results_p_0_5_beta10 <- read.table(paste0(results_loc_p_0_5_beta10,"/ror.csv"), header = T)
ror_results_p_0_5_beta50 <- read.table(paste0(results_loc_p_0_5_beta50,"/ror.csv"), header = T)
ror_results_p_0_5_beta100 <- read.table(paste0(results_loc_p_0_5_beta100,"/ror.csv"), header = T)
```

## fixed beta and fixed p

```{r b_1_p_0_1}
conf_thresh <- as.factor(c(0.4,0.5,0.6,0.7))
prr_thresh <- as.factor(c(1,1.2,1.5,2))
rr_thresh <- as.factor(c(1,1.2,1.5,2))
ror_thresh <- as.factor(c(1,1.2,1.5,2))

#sensitivity plots
#confidence thresholds
mean_sens_conf <- as.numeric(conf_results_p_0_1_beta1[1,])

#prr thresholds
mean_sens_prr <- as.numeric(prr_results_p_0_1_beta1[1,])

#rr thresholds
mean_sens_rr <- as.numeric(rr_results_p_0_1_beta1[1,])

#ror thresholds
mean_sens_ror <- as.numeric(ror_results_p_0_1_beta1[1,])

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_sens_conf, group=1)) + 
  geom_point(aes(x=conf_thresh, y=mean_sens_conf, group=1)) + 
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_sens_prr, group=1)) + 
  geom_point(aes(x=prr_thresh, y=mean_sens_prr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_sens_rr, group=1)) + 
  geom_point(aes(x=rr_thresh, y=mean_sens_rr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_sens_ror, group=1)) + 
  geom_point(aes(x=ror_thresh, y=mean_sens_ror, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_sens_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2, top = "Sensitivity plots for Setting 1 (\U03B2 = 1, p = 0.1)")

#final combined Sensitivity plot with common legend
#combined_sens_plot <- grid.arrange(combined_plot, nrow=2, heights=c(8.5,2), top = "Sensitivity plots for 1 drug and 3 AEs setting - beta = 1, p = 0.1")
sens_plot_file <- "/Users/reetikasarkar/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_beta_fixed_p/beta1_p0_1/sens.png"
combined_sens_plot
ggsave(filename = sens_plot_file, plot = combined_sens_plot)

## specificity plots
#confidence thresholds
mean_spec_conf <- as.numeric(conf_results_p_0_1_beta1[2,])

#prr thresholds
mean_spec_prr <- as.numeric(prr_results_p_0_1_beta1[2,])

#rr thresholds
mean_spec_rr <- as.numeric(rr_results_p_0_1_beta1[2,])

#ror thresholds
mean_spec_ror <- as.numeric(ror_results_p_0_1_beta1[2,])

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_spec_conf, group=1)) + 
  geom_point(aes(x=conf_thresh, y=mean_spec_conf, group=1)) + 
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_spec_prr, group=1)) + 
  geom_point(aes(x=prr_thresh, y=mean_spec_prr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_spec_rr, group=1)) + 
  geom_point(aes(x=rr_thresh, y=mean_spec_rr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_spec_ror, group=1)) + 
  geom_point(aes(x=ror_thresh, y=mean_spec_ror, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_spec_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2, top = "Specificity plots for Setting 1 (\U03B2 = 1, p = 0.1)")

spec_plot_file <- "/Users/reetikasarkar/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_beta_fixed_p/beta1_p0_1/spec.png"
combined_spec_plot
ggsave(filename = spec_plot_file, plot = combined_spec_plot)

## overall accuracy plots
#confidence thresholds
mean_acc_conf <- as.numeric(conf_results_p_0_1_beta1[5,])

#prr thresholds
mean_acc_prr <- as.numeric(prr_results_p_0_1_beta1[5,])

#rr thresholds
mean_acc_rr <- as.numeric(rr_results_p_0_1_beta1[5,])

#ror thresholds
mean_acc_ror <- as.numeric(ror_results_p_0_1_beta1[5,])

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_acc_conf, group=1)) + 
  geom_point(aes(x=conf_thresh, y=mean_acc_conf, group=1)) + 
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_acc_prr, group=1)) + 
  geom_point(aes(x=prr_thresh, y=mean_acc_prr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_acc_rr, group=1)) + 
  geom_point(aes(x=rr_thresh, y=mean_acc_rr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_acc_ror, group=1)) + 
  geom_point(aes(x=ror_thresh, y=mean_acc_ror, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_acc_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2, top = "Overall Accuracy plots for Setting 1 (\U03B2 = 1, p = 0.1)")

acc_plot_file <- "/Users/reetikasarkar/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_beta_fixed_p/beta1_p0_1/acc.png"
combined_acc_plot
ggsave(filename = acc_plot_file, plot = combined_acc_plot)
```

```{r b_1_p_0_3}
conf_thresh <- as.factor(c(0.4,0.5,0.6,0.7))
prr_thresh <- as.factor(c(1,1.2,1.5,2))
rr_thresh <- as.factor(c(1,1.2,1.5,2))
ror_thresh <- as.factor(c(1,1.2,1.5,2))

#sensitivity plots
#confidence thresholds
mean_sens_conf <- as.numeric(conf_results_p_0_3_beta1[1,])

#prr thresholds
mean_sens_prr <- as.numeric(prr_results_p_0_3_beta1[1,])

#rr thresholds
mean_sens_rr <- as.numeric(rr_results_p_0_3_beta1[1,])

#ror thresholds
mean_sens_ror <- as.numeric(ror_results_p_0_3_beta1[1,])

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_sens_conf, group=1)) + 
  geom_point(aes(x=conf_thresh, y=mean_sens_conf, group=1)) + 
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_sens_prr, group=1)) + 
  geom_point(aes(x=prr_thresh, y=mean_sens_prr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_sens_rr, group=1)) + 
  geom_point(aes(x=rr_thresh, y=mean_sens_rr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_sens_ror, group=1)) + 
  geom_point(aes(x=ror_thresh, y=mean_sens_ror, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_sens_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2, top = "Sensitivity plots for Setting 1 (\U03B2 = 1, p = 0.3)")

#final combined Sensitivity plot with common legend
#combined_sens_plot <- grid.arrange(combined_plot, nrow=2, heights=c(8.5,2), top = "Sensitivity plots for 1 drug and 3 AEs setting - beta = 1, p = 0.1")
sens_plot_file <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_beta_fixed_p/beta1_p0_3/sens.png"
combined_sens_plot
ggsave(filename = sens_plot_file, plot = combined_sens_plot)

## specificity plots
#confidence thresholds
mean_spec_conf <- as.numeric(conf_results_p_0_3_beta1[2,])

#prr thresholds
mean_spec_prr <- as.numeric(prr_results_p_0_3_beta1[2,])

#rr thresholds
mean_spec_rr <- as.numeric(rr_results_p_0_3_beta1[2,])

#ror thresholds
mean_spec_ror <- as.numeric(ror_results_p_0_3_beta1[2,])

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_spec_conf, group=1)) + 
  geom_point(aes(x=conf_thresh, y=mean_spec_conf, group=1)) + 
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_spec_prr, group=1)) + 
  geom_point(aes(x=prr_thresh, y=mean_spec_prr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_spec_rr, group=1)) + 
  geom_point(aes(x=rr_thresh, y=mean_spec_rr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_spec_ror, group=1)) + 
  geom_point(aes(x=ror_thresh, y=mean_spec_ror, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_spec_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2, top = "Specificity plots for Setting 1 (\U03B2 = 1, p = 0.3)")

spec_plot_file <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_beta_fixed_p/beta1_p0_3/spec.png"
combined_spec_plot
ggsave(filename = spec_plot_file, plot = combined_spec_plot)

## overall accuracy plots
#confidence thresholds
mean_acc_conf <- as.numeric(conf_results_p_0_3_beta1[5,])

#prr thresholds
mean_acc_prr <- as.numeric(prr_results_p_0_3_beta1[5,])

#rr thresholds
mean_acc_rr <- as.numeric(rr_results_p_0_3_beta1[5,])

#ror thresholds
mean_acc_ror <- as.numeric(ror_results_p_0_3_beta1[5,])

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_acc_conf, group=1)) + 
  geom_point(aes(x=conf_thresh, y=mean_acc_conf, group=1)) + 
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_acc_prr, group=1)) + 
  geom_point(aes(x=prr_thresh, y=mean_acc_prr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_acc_rr, group=1)) + 
  geom_point(aes(x=rr_thresh, y=mean_acc_rr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_acc_ror, group=1)) + 
  geom_point(aes(x=ror_thresh, y=mean_acc_ror, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_acc_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2, top = "Overall Accuracy plots for Setting 1 (\U03B2 = 1, p = 0.3)")

acc_plot_file <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_beta_fixed_p/beta1_p0_3/acc.png"
combined_acc_plot
ggsave(filename = acc_plot_file, plot = combined_acc_plot)
```

```{r b_1_p_0_5}
conf_thresh <- as.factor(c(0.4,0.5,0.6,0.7))
prr_thresh <- as.factor(c(1,1.2,1.5,2))
rr_thresh <- as.factor(c(1,1.2,1.5,2))
ror_thresh <- as.factor(c(1,1.2,1.5,2))

#sensitivity plots
#confidence thresholds
mean_sens_conf <- as.numeric(conf_results_p_0_5_beta1[1,])

#prr thresholds
mean_sens_prr <- as.numeric(prr_results_p_0_5_beta1[1,])

#rr thresholds
mean_sens_rr <- as.numeric(rr_results_p_0_5_beta1[1,])

#ror thresholds
mean_sens_ror <- as.numeric(ror_results_p_0_5_beta1[1,])

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_sens_conf, group=1)) + 
  geom_point(aes(x=conf_thresh, y=mean_sens_conf, group=1)) + 
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_sens_prr, group=1)) + 
  geom_point(aes(x=prr_thresh, y=mean_sens_prr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_sens_rr, group=1)) + 
  geom_point(aes(x=rr_thresh, y=mean_sens_rr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_sens_ror, group=1)) + 
  geom_point(aes(x=ror_thresh, y=mean_sens_ror, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_sens_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2, top = "Sensitivity plots for Setting 1 (\U03B2 = 1, p = 0.5)")

#final combined Sensitivity plot with common legend
#combined_sens_plot <- grid.arrange(combined_plot, nrow=2, heights=c(8.5,2), top = "Sensitivity plots for 1 drug and 3 AEs setting - beta = 1, p = 0.1")
sens_plot_file <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_beta_fixed_p/beta1_p0_5/sens.png"
combined_sens_plot
ggsave(filename = sens_plot_file, plot = combined_sens_plot)

## specificity plots
#confidence thresholds
mean_spec_conf <- as.numeric(conf_results_p_0_5_beta1[2,])

#prr thresholds
mean_spec_prr <- as.numeric(prr_results_p_0_5_beta1[2,])

#rr thresholds
mean_spec_rr <- as.numeric(rr_results_p_0_5_beta1[2,])

#ror thresholds
mean_spec_ror <- as.numeric(ror_results_p_0_5_beta1[2,])

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_spec_conf, group=1)) + 
  geom_point(aes(x=conf_thresh, y=mean_spec_conf, group=1)) + 
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_spec_prr, group=1)) + 
  geom_point(aes(x=prr_thresh, y=mean_spec_prr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_spec_rr, group=1)) + 
  geom_point(aes(x=rr_thresh, y=mean_spec_rr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_spec_ror, group=1)) + 
  geom_point(aes(x=ror_thresh, y=mean_spec_ror, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_spec_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2, top = "Specificity plots for Setting 1 (\U03B2 = 1, p = 0.5)")

spec_plot_file <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_beta_fixed_p/beta1_p0_5/spec.png"
combined_spec_plot
ggsave(filename = spec_plot_file, plot = combined_spec_plot)

## overall accuracy plots
#confidence thresholds
mean_acc_conf <- as.numeric(conf_results_p_0_5_beta1[5,])

#prr thresholds
mean_acc_prr <- as.numeric(prr_results_p_0_5_beta1[5,])

#rr thresholds
mean_acc_rr <- as.numeric(rr_results_p_0_5_beta1[5,])

#ror thresholds
mean_acc_ror <- as.numeric(ror_results_p_0_5_beta1[5,])

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_acc_conf, group=1)) + 
  geom_point(aes(x=conf_thresh, y=mean_acc_conf, group=1)) + 
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_acc_prr, group=1)) + 
  geom_point(aes(x=prr_thresh, y=mean_acc_prr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_acc_rr, group=1)) + 
  geom_point(aes(x=rr_thresh, y=mean_acc_rr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_acc_ror, group=1)) + 
  geom_point(aes(x=ror_thresh, y=mean_acc_ror, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_acc_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2, top = "Overall Accuracy plots for Setting 1 (\U03B2 = 1, p = 0.5)")

acc_plot_file <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_beta_fixed_p/beta1_p0_5/acc.png"
combined_acc_plot
ggsave(filename = acc_plot_file, plot = combined_acc_plot)
```

```{r b_10_p_0_1}
conf_thresh <- as.factor(c(0.4,0.5,0.6,0.7))
prr_thresh <- as.factor(c(1,1.2,1.5,2))
rr_thresh <- as.factor(c(1,1.2,1.5,2))
ror_thresh <- as.factor(c(1,1.2,1.5,2))

#sensitivity plots
#confidence thresholds
mean_sens_conf <- as.numeric(conf_results_p_0_1_beta10[1,])

#prr thresholds
mean_sens_prr <- as.numeric(prr_results_p_0_1_beta10[1,])

#rr thresholds
mean_sens_rr <- as.numeric(rr_results_p_0_1_beta10[1,])

#ror thresholds
mean_sens_ror <- as.numeric(ror_results_p_0_1_beta10[1,])

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_sens_conf, group=1)) + 
  geom_point(aes(x=conf_thresh, y=mean_sens_conf, group=1)) + 
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_sens_prr, group=1)) + 
  geom_point(aes(x=prr_thresh, y=mean_sens_prr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_sens_rr, group=1)) + 
  geom_point(aes(x=rr_thresh, y=mean_sens_rr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_sens_ror, group=1)) + 
  geom_point(aes(x=ror_thresh, y=mean_sens_ror, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_sens_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2, top = "Sensitivity plots for Setting 1 (\U03B2 = 10, p = 0.1)")

#final combined Sensitivity plot with common legend
#combined_sens_plot <- grid.arrange(combined_plot, nrow=2, heights=c(8.5,2), top = "Sensitivity plots for 1 drug and 3 AEs setting - beta = 1, p = 0.1")
sens_plot_file <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_beta_fixed_p/beta10_p0_1/sens.png"
combined_sens_plot
ggsave(filename = sens_plot_file, plot = combined_sens_plot)

## specificity plots
#confidence thresholds
mean_spec_conf <- as.numeric(conf_results_p_0_1_beta10[2,])

#prr thresholds
mean_spec_prr <- as.numeric(prr_results_p_0_1_beta10[2,])

#rr thresholds
mean_spec_rr <- as.numeric(rr_results_p_0_1_beta10[2,])

#ror thresholds
mean_spec_ror <- as.numeric(ror_results_p_0_1_beta10[2,])

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_spec_conf, group=1)) + 
  geom_point(aes(x=conf_thresh, y=mean_spec_conf, group=1)) + 
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_spec_prr, group=1)) + 
  geom_point(aes(x=prr_thresh, y=mean_spec_prr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_spec_rr, group=1)) + 
  geom_point(aes(x=rr_thresh, y=mean_spec_rr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_spec_ror, group=1)) + 
  geom_point(aes(x=ror_thresh, y=mean_spec_ror, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_spec_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2, top = "Specificity plots for Setting 1 (\U03B2 = 10, p = 0.1)")

spec_plot_file <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_beta_fixed_p/beta10_p0_1/spec.png"
combined_spec_plot
ggsave(filename = spec_plot_file, plot = combined_spec_plot)

## overall accuracy plots
#confidence thresholds
mean_acc_conf <- as.numeric(conf_results_p_0_1_beta10[5,])

#prr thresholds
mean_acc_prr <- as.numeric(prr_results_p_0_1_beta10[5,])

#rr thresholds
mean_acc_rr <- as.numeric(rr_results_p_0_1_beta10[5,])

#ror thresholds
mean_acc_ror <- as.numeric(ror_results_p_0_1_beta10[5,])

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_acc_conf, group=1)) + 
  geom_point(aes(x=conf_thresh, y=mean_acc_conf, group=1)) + 
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_acc_prr, group=1)) + 
  geom_point(aes(x=prr_thresh, y=mean_acc_prr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_acc_rr, group=1)) + 
  geom_point(aes(x=rr_thresh, y=mean_acc_rr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_acc_ror, group=1)) + 
  geom_point(aes(x=ror_thresh, y=mean_acc_ror, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_acc_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2, top = "Overall Accuracy plots for Setting 1 (\U03B2 = 10, p = 0.1)")

acc_plot_file <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_beta_fixed_p/beta10_p0_1/acc.png"
combined_acc_plot
ggsave(filename = acc_plot_file, plot = combined_acc_plot)
```

```{r b_10_p_0_3}
conf_thresh <- as.factor(c(0.4,0.5,0.6,0.7))
prr_thresh <- as.factor(c(1,1.2,1.5,2))
rr_thresh <- as.factor(c(1,1.2,1.5,2))
ror_thresh <- as.factor(c(1,1.2,1.5,2))

#sensitivity plots
#confidence thresholds
mean_sens_conf <- as.numeric(conf_results_p_0_3_beta10[1,])

#prr thresholds
mean_sens_prr <- as.numeric(prr_results_p_0_3_beta10[1,])

#rr thresholds
mean_sens_rr <- as.numeric(rr_results_p_0_3_beta10[1,])

#ror thresholds
mean_sens_ror <- as.numeric(ror_results_p_0_3_beta10[1,])

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_sens_conf, group=1)) + 
  geom_point(aes(x=conf_thresh, y=mean_sens_conf, group=1)) + 
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_sens_prr, group=1)) + 
  geom_point(aes(x=prr_thresh, y=mean_sens_prr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_sens_rr, group=1)) + 
  geom_point(aes(x=rr_thresh, y=mean_sens_rr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_sens_ror, group=1)) + 
  geom_point(aes(x=ror_thresh, y=mean_sens_ror, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_sens_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2, top = "Sensitivity plots for Setting 1 (\U03B2 = 10, p = 0.3)")

#final combined Sensitivity plot with common legend
#combined_sens_plot <- grid.arrange(combined_plot, nrow=2, heights=c(8.5,2), top = "Sensitivity plots for 1 drug and 3 AEs setting - beta = 1, p = 0.1")
sens_plot_file <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_beta_fixed_p/beta10_p0_3/sens.png"
combined_sens_plot
ggsave(filename = sens_plot_file, plot = combined_sens_plot)

## specificity plots
#confidence thresholds
mean_spec_conf <- as.numeric(conf_results_p_0_3_beta10[2,])

#prr thresholds
mean_spec_prr <- as.numeric(prr_results_p_0_3_beta10[2,])

#rr thresholds
mean_spec_rr <- as.numeric(rr_results_p_0_3_beta10[2,])

#ror thresholds
mean_spec_ror <- as.numeric(ror_results_p_0_3_beta10[2,])

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_spec_conf, group=1)) + 
  geom_point(aes(x=conf_thresh, y=mean_spec_conf, group=1)) + 
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_spec_prr, group=1)) + 
  geom_point(aes(x=prr_thresh, y=mean_spec_prr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_spec_rr, group=1)) + 
  geom_point(aes(x=rr_thresh, y=mean_spec_rr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_spec_ror, group=1)) + 
  geom_point(aes(x=ror_thresh, y=mean_spec_ror, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_spec_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2, top = "Specificity plots for Setting 1 (\U03B2 = 10, p = 0.3)")

spec_plot_file <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_beta_fixed_p/beta10_p0_3/spec.png"
combined_spec_plot
ggsave(filename = spec_plot_file, plot = combined_spec_plot)

## overall accuracy plots
#confidence thresholds
mean_acc_conf <- as.numeric(conf_results_p_0_3_beta10[5,])

#prr thresholds
mean_acc_prr <- as.numeric(prr_results_p_0_3_beta10[5,])

#rr thresholds
mean_acc_rr <- as.numeric(rr_results_p_0_3_beta10[5,])

#ror thresholds
mean_acc_ror <- as.numeric(ror_results_p_0_3_beta10[5,])

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_acc_conf, group=1)) + 
  geom_point(aes(x=conf_thresh, y=mean_acc_conf, group=1)) + 
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_acc_prr, group=1)) + 
  geom_point(aes(x=prr_thresh, y=mean_acc_prr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_acc_rr, group=1)) + 
  geom_point(aes(x=rr_thresh, y=mean_acc_rr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_acc_ror, group=1)) + 
  geom_point(aes(x=ror_thresh, y=mean_acc_ror, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_acc_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2, top = "Overall Accuracy plots for Setting 1 (\U03B2 = 10, p = 0.3)")

acc_plot_file <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_beta_fixed_p/beta10_p0_3/acc.png"
combined_acc_plot
ggsave(filename = acc_plot_file, plot = combined_acc_plot)
```

```{r b_10_p_0_5}
conf_thresh <- as.factor(c(0.4,0.5,0.6,0.7))
prr_thresh <- as.factor(c(1,1.2,1.5,2))
rr_thresh <- as.factor(c(1,1.2,1.5,2))
ror_thresh <- as.factor(c(1,1.2,1.5,2))

#sensitivity plots
#confidence thresholds
mean_sens_conf <- as.numeric(conf_results_p_0_5_beta10[1,])

#prr thresholds
mean_sens_prr <- as.numeric(prr_results_p_0_5_beta10[1,])

#rr thresholds
mean_sens_rr <- as.numeric(rr_results_p_0_5_beta10[1,])

#ror thresholds
mean_sens_ror <- as.numeric(ror_results_p_0_5_beta10[1,])

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_sens_conf, group=1)) + 
  geom_point(aes(x=conf_thresh, y=mean_sens_conf, group=1)) + 
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_sens_prr, group=1)) + 
  geom_point(aes(x=prr_thresh, y=mean_sens_prr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_sens_rr, group=1)) + 
  geom_point(aes(x=rr_thresh, y=mean_sens_rr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_sens_ror, group=1)) + 
  geom_point(aes(x=ror_thresh, y=mean_sens_ror, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_sens_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2, top = "Sensitivity plots for Setting 1 (\U03B2 = 10, p = 0.5)")

#final combined Sensitivity plot with common legend
#combined_sens_plot <- grid.arrange(combined_plot, nrow=2, heights=c(8.5,2), top = "Sensitivity plots for 1 drug and 3 AEs setting - beta = 1, p = 0.1")
sens_plot_file <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_beta_fixed_p/beta10_p0_5/sens.png"
combined_sens_plot
ggsave(filename = sens_plot_file, plot = combined_sens_plot)

## specificity plots
#confidence thresholds
mean_spec_conf <- as.numeric(conf_results_p_0_5_beta10[2,])

#prr thresholds
mean_spec_prr <- as.numeric(prr_results_p_0_5_beta10[2,])

#rr thresholds
mean_spec_rr <- as.numeric(rr_results_p_0_5_beta10[2,])

#ror thresholds
mean_spec_ror <- as.numeric(ror_results_p_0_5_beta10[2,])

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_spec_conf, group=1)) + 
  geom_point(aes(x=conf_thresh, y=mean_spec_conf, group=1)) + 
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_spec_prr, group=1)) + 
  geom_point(aes(x=prr_thresh, y=mean_spec_prr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_spec_rr, group=1)) + 
  geom_point(aes(x=rr_thresh, y=mean_spec_rr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_spec_ror, group=1)) + 
  geom_point(aes(x=ror_thresh, y=mean_spec_ror, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_spec_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2, top = "Specificity plots for Setting 1 (\U03B2 = 10, p = 0.5)")

spec_plot_file <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_beta_fixed_p/beta10_p0_5/spec.png"
combined_spec_plot
ggsave(filename = spec_plot_file, plot = combined_spec_plot)

## overall accuracy plots
#confidence thresholds
mean_acc_conf <- as.numeric(conf_results_p_0_5_beta10[5,])

#prr thresholds
mean_acc_prr <- as.numeric(prr_results_p_0_5_beta10[5,])

#rr thresholds
mean_acc_rr <- as.numeric(rr_results_p_0_5_beta10[5,])

#ror thresholds
mean_acc_ror <- as.numeric(ror_results_p_0_5_beta10[5,])

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_acc_conf, group=1)) + 
  geom_point(aes(x=conf_thresh, y=mean_acc_conf, group=1)) + 
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_acc_prr, group=1)) + 
  geom_point(aes(x=prr_thresh, y=mean_acc_prr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_acc_rr, group=1)) + 
  geom_point(aes(x=rr_thresh, y=mean_acc_rr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_acc_ror, group=1)) + 
  geom_point(aes(x=ror_thresh, y=mean_acc_ror, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_acc_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2, top = "Overall Accuracy plots for Setting 1 (\U03B2 = 10, p = 0.5)")

acc_plot_file <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_beta_fixed_p/beta10_p0_5/acc.png"
combined_acc_plot
ggsave(filename = acc_plot_file, plot = combined_acc_plot)
```

```{r b_50_p_0_1}
conf_thresh <- as.factor(c(0.4,0.5,0.6,0.7))
prr_thresh <- as.factor(c(1,1.2,1.5,2))
rr_thresh <- as.factor(c(1,1.2,1.5,2))
ror_thresh <- as.factor(c(1,1.2,1.5,2))

#sensitivity plots
#confidence thresholds
mean_sens_conf <- as.numeric(conf_results_p_0_1_beta50[1,])

#prr thresholds
mean_sens_prr <- as.numeric(prr_results_p_0_1_beta50[1,])

#rr thresholds
mean_sens_rr <- as.numeric(rr_results_p_0_1_beta50[1,])

#ror thresholds
mean_sens_ror <- as.numeric(ror_results_p_0_1_beta50[1,])

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_sens_conf, group=1)) + 
  geom_point(aes(x=conf_thresh, y=mean_sens_conf, group=1)) + 
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_sens_prr, group=1)) + 
  geom_point(aes(x=prr_thresh, y=mean_sens_prr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_sens_rr, group=1)) + 
  geom_point(aes(x=rr_thresh, y=mean_sens_rr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_sens_ror, group=1)) + 
  geom_point(aes(x=ror_thresh, y=mean_sens_ror, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_sens_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2, top = "Sensitivity plots for Setting 1 (\U03B2 = 50, p = 0.1)")

#final combined Sensitivity plot with common legend
#combined_sens_plot <- grid.arrange(combined_plot, nrow=2, heights=c(8.5,2), top = "Sensitivity plots for 1 drug and 3 AEs setting - beta = 1, p = 0.1")
sens_plot_file <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_beta_fixed_p/beta50_p0_1/sens.png"
combined_sens_plot
ggsave(filename = sens_plot_file, plot = combined_sens_plot)

## specificity plots
#confidence thresholds
mean_spec_conf <- as.numeric(conf_results_p_0_1_beta50[2,])

#prr thresholds
mean_spec_prr <- as.numeric(prr_results_p_0_1_beta50[2,])

#rr thresholds
mean_spec_rr <- as.numeric(rr_results_p_0_1_beta50[2,])

#ror thresholds
mean_spec_ror <- as.numeric(ror_results_p_0_1_beta50[2,])

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_spec_conf, group=1)) + 
  geom_point(aes(x=conf_thresh, y=mean_spec_conf, group=1)) + 
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_spec_prr, group=1)) + 
  geom_point(aes(x=prr_thresh, y=mean_spec_prr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_spec_rr, group=1)) + 
  geom_point(aes(x=rr_thresh, y=mean_spec_rr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_spec_ror, group=1)) + 
  geom_point(aes(x=ror_thresh, y=mean_spec_ror, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_spec_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2, top = "Specificity plots for Setting 1 (\U03B2 = 50, p = 0.1)")

spec_plot_file <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_beta_fixed_p/beta50_p0_1/spec.png"
combined_spec_plot
ggsave(filename = spec_plot_file, plot = combined_spec_plot)

## overall accuracy plots
#confidence thresholds
mean_acc_conf <- as.numeric(conf_results_p_0_1_beta50[5,])

#prr thresholds
mean_acc_prr <- as.numeric(prr_results_p_0_1_beta50[5,])

#rr thresholds
mean_acc_rr <- as.numeric(rr_results_p_0_1_beta50[5,])

#ror thresholds
mean_acc_ror <- as.numeric(ror_results_p_0_1_beta50[5,])

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_acc_conf, group=1)) + 
  geom_point(aes(x=conf_thresh, y=mean_acc_conf, group=1)) + 
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_acc_prr, group=1)) + 
  geom_point(aes(x=prr_thresh, y=mean_acc_prr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_acc_rr, group=1)) + 
  geom_point(aes(x=rr_thresh, y=mean_acc_rr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_acc_ror, group=1)) + 
  geom_point(aes(x=ror_thresh, y=mean_acc_ror, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_acc_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2, top = "Overall Accuracy plots for Setting 1 (\U03B2 = 50, p = 0.1)")

acc_plot_file <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_beta_fixed_p/beta50_p0_1/acc.png"
combined_acc_plot
ggsave(filename = acc_plot_file, plot = combined_acc_plot)
```

```{r b_50_p_0_3}
conf_thresh <- as.factor(c(0.4,0.5,0.6,0.7))
prr_thresh <- as.factor(c(1,1.2,1.5,2))
rr_thresh <- as.factor(c(1,1.2,1.5,2))
ror_thresh <- as.factor(c(1,1.2,1.5,2))

#sensitivity plots
#confidence thresholds
mean_sens_conf <- as.numeric(conf_results_p_0_3_beta50[1,])

#prr thresholds
mean_sens_prr <- as.numeric(prr_results_p_0_3_beta50[1,])

#rr thresholds
mean_sens_rr <- as.numeric(rr_results_p_0_3_beta50[1,])

#ror thresholds
mean_sens_ror <- as.numeric(ror_results_p_0_3_beta50[1,])

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_sens_conf, group=1)) + 
  geom_point(aes(x=conf_thresh, y=mean_sens_conf, group=1)) + 
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_sens_prr, group=1)) + 
  geom_point(aes(x=prr_thresh, y=mean_sens_prr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_sens_rr, group=1)) + 
  geom_point(aes(x=rr_thresh, y=mean_sens_rr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_sens_ror, group=1)) + 
  geom_point(aes(x=ror_thresh, y=mean_sens_ror, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_sens_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2, top = "Sensitivity plots for Setting 1 (\U03B2 = 50, p = 0.3)")

#final combined Sensitivity plot with common legend
#combined_sens_plot <- grid.arrange(combined_plot, nrow=2, heights=c(8.5,2), top = "Sensitivity plots for 1 drug and 3 AEs setting - beta = 1, p = 0.1")
sens_plot_file <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_beta_fixed_p/beta50_p0_3/sens.png"
combined_sens_plot
ggsave(filename = sens_plot_file, plot = combined_sens_plot)

## specificity plots
#confidence thresholds
mean_spec_conf <- as.numeric(conf_results_p_0_3_beta50[2,])

#prr thresholds
mean_spec_prr <- as.numeric(prr_results_p_0_3_beta50[2,])

#rr thresholds
mean_spec_rr <- as.numeric(rr_results_p_0_3_beta50[2,])

#ror thresholds
mean_spec_ror <- as.numeric(ror_results_p_0_3_beta50[2,])

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_spec_conf, group=1)) + 
  geom_point(aes(x=conf_thresh, y=mean_spec_conf, group=1)) + 
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_spec_prr, group=1)) + 
  geom_point(aes(x=prr_thresh, y=mean_spec_prr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_spec_rr, group=1)) + 
  geom_point(aes(x=rr_thresh, y=mean_spec_rr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_spec_ror, group=1)) + 
  geom_point(aes(x=ror_thresh, y=mean_spec_ror, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_spec_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2, top = "Specificity plots for Setting 1 (\U03B2 = 50, p = 0.3)")

spec_plot_file <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_beta_fixed_p/beta50_p0_3/spec.png"
combined_spec_plot
ggsave(filename = spec_plot_file, plot = combined_spec_plot)

## overall accuracy plots
#confidence thresholds
mean_acc_conf <- as.numeric(conf_results_p_0_3_beta50[5,])

#prr thresholds
mean_acc_prr <- as.numeric(prr_results_p_0_3_beta50[5,])

#rr thresholds
mean_acc_rr <- as.numeric(rr_results_p_0_3_beta50[5,])

#ror thresholds
mean_acc_ror <- as.numeric(ror_results_p_0_3_beta50[5,])

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_acc_conf, group=1)) + 
  geom_point(aes(x=conf_thresh, y=mean_acc_conf, group=1)) + 
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_acc_prr, group=1)) + 
  geom_point(aes(x=prr_thresh, y=mean_acc_prr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_acc_rr, group=1)) + 
  geom_point(aes(x=rr_thresh, y=mean_acc_rr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_acc_ror, group=1)) + 
  geom_point(aes(x=ror_thresh, y=mean_acc_ror, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_acc_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2, top = "Overall Accuracy plots for Setting 1 (\U03B2 = 50, p = 0.3)")

acc_plot_file <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_beta_fixed_p/beta50_p0_3/acc.png"
combined_acc_plot
ggsave(filename = acc_plot_file, plot = combined_acc_plot)
```

```{r b_50_p_0_5}
conf_thresh <- as.factor(c(0.4,0.5,0.6,0.7))
prr_thresh <- as.factor(c(1,1.2,1.5,2))
rr_thresh <- as.factor(c(1,1.2,1.5,2))
ror_thresh <- as.factor(c(1,1.2,1.5,2))

#sensitivity plots
#confidence thresholds
mean_sens_conf <- as.numeric(conf_results_p_0_5_beta50[1,])

#prr thresholds
mean_sens_prr <- as.numeric(prr_results_p_0_5_beta50[1,])

#rr thresholds
mean_sens_rr <- as.numeric(rr_results_p_0_5_beta50[1,])

#ror thresholds
mean_sens_ror <- as.numeric(ror_results_p_0_5_beta50[1,])

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_sens_conf, group=1)) + 
  geom_point(aes(x=conf_thresh, y=mean_sens_conf, group=1)) + 
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_sens_prr, group=1)) + 
  geom_point(aes(x=prr_thresh, y=mean_sens_prr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_sens_rr, group=1)) + 
  geom_point(aes(x=rr_thresh, y=mean_sens_rr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_sens_ror, group=1)) + 
  geom_point(aes(x=ror_thresh, y=mean_sens_ror, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_sens_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2, top = "Sensitivity plots for Setting 1 (\U03B2 = 50, p = 0.5)")

#final combined Sensitivity plot with common legend
#combined_sens_plot <- grid.arrange(combined_plot, nrow=2, heights=c(8.5,2), top = "Sensitivity plots for 1 drug and 3 AEs setting - beta = 1, p = 0.1")
sens_plot_file <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_beta_fixed_p/beta50_p0_5/sens.png"
combined_sens_plot
ggsave(filename = sens_plot_file, plot = combined_sens_plot)

## specificity plots
#confidence thresholds
mean_spec_conf <- as.numeric(conf_results_p_0_5_beta50[2,])

#prr thresholds
mean_spec_prr <- as.numeric(prr_results_p_0_5_beta50[2,])

#rr thresholds
mean_spec_rr <- as.numeric(rr_results_p_0_5_beta50[2,])

#ror thresholds
mean_spec_ror <- as.numeric(ror_results_p_0_5_beta50[2,])

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_spec_conf, group=1)) + 
  geom_point(aes(x=conf_thresh, y=mean_spec_conf, group=1)) + 
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_spec_prr, group=1)) + 
  geom_point(aes(x=prr_thresh, y=mean_spec_prr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_spec_rr, group=1)) + 
  geom_point(aes(x=rr_thresh, y=mean_spec_rr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_spec_ror, group=1)) + 
  geom_point(aes(x=ror_thresh, y=mean_spec_ror, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_spec_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2, top = "Specificity plots for Setting 1 (\U03B2 = 50, p = 0.5)")

spec_plot_file <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_beta_fixed_p/beta50_p0_5/spec.png"
combined_spec_plot
ggsave(filename = spec_plot_file, plot = combined_spec_plot)

## overall accuracy plots
#confidence thresholds
mean_acc_conf <- as.numeric(conf_results_p_0_5_beta50[5,])

#prr thresholds
mean_acc_prr <- as.numeric(prr_results_p_0_5_beta50[5,])

#rr thresholds
mean_acc_rr <- as.numeric(rr_results_p_0_5_beta50[5,])

#ror thresholds
mean_acc_ror <- as.numeric(ror_results_p_0_5_beta50[5,])

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_acc_conf, group=1)) + 
  geom_point(aes(x=conf_thresh, y=mean_acc_conf, group=1)) + 
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_acc_prr, group=1)) + 
  geom_point(aes(x=prr_thresh, y=mean_acc_prr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_acc_rr, group=1)) + 
  geom_point(aes(x=rr_thresh, y=mean_acc_rr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_acc_ror, group=1)) + 
  geom_point(aes(x=ror_thresh, y=mean_acc_ror, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_acc_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2, top = "Overall Accuracy plots for Setting 1 (\U03B2 = 50, p = 0.5)")

acc_plot_file <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_beta_fixed_p/beta50_p0_5/acc.png"
combined_acc_plot
ggsave(filename = acc_plot_file, plot = combined_acc_plot)
```

```{r b_100_p_0_1}
conf_thresh <- as.factor(c(0.4,0.5,0.6,0.7))
prr_thresh <- as.factor(c(1,1.2,1.5,2))
rr_thresh <- as.factor(c(1,1.2,1.5,2))
ror_thresh <- as.factor(c(1,1.2,1.5,2))

#sensitivity plots
#confidence thresholds
mean_sens_conf <- as.numeric(conf_results_p_0_1_beta100[1,])

#prr thresholds
mean_sens_prr <- as.numeric(prr_results_p_0_1_beta100[1,])

#rr thresholds
mean_sens_rr <- as.numeric(rr_results_p_0_1_beta100[1,])

#ror thresholds
mean_sens_ror <- as.numeric(ror_results_p_0_1_beta100[1,])

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_sens_conf, group=1)) + 
  geom_point(aes(x=conf_thresh, y=mean_sens_conf, group=1)) + 
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_sens_prr, group=1)) + 
  geom_point(aes(x=prr_thresh, y=mean_sens_prr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_sens_rr, group=1)) + 
  geom_point(aes(x=rr_thresh, y=mean_sens_rr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_sens_ror, group=1)) + 
  geom_point(aes(x=ror_thresh, y=mean_sens_ror, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_sens_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2, top = "Sensitivity plots for Setting 1 (\U03B2 = 100, p = 0.1)")

#final combined Sensitivity plot with common legend
#combined_sens_plot <- grid.arrange(combined_plot, nrow=2, heights=c(8.5,2), top = "Sensitivity plots for 1 drug and 3 AEs setting - beta = 1, p = 0.1")
sens_plot_file <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_beta_fixed_p/beta100_p0_1/sens.png"
combined_sens_plot
ggsave(filename = sens_plot_file, plot = combined_sens_plot)

## specificity plots
#confidence thresholds
mean_spec_conf <- as.numeric(conf_results_p_0_1_beta100[2,])

#prr thresholds
mean_spec_prr <- as.numeric(prr_results_p_0_1_beta100[2,])

#rr thresholds
mean_spec_rr <- as.numeric(rr_results_p_0_1_beta100[2,])

#ror thresholds
mean_spec_ror <- as.numeric(ror_results_p_0_1_beta100[2,])

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_spec_conf, group=1)) + 
  geom_point(aes(x=conf_thresh, y=mean_spec_conf, group=1)) + 
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_spec_prr, group=1)) + 
  geom_point(aes(x=prr_thresh, y=mean_spec_prr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_spec_rr, group=1)) + 
  geom_point(aes(x=rr_thresh, y=mean_spec_rr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_spec_ror, group=1)) + 
  geom_point(aes(x=ror_thresh, y=mean_spec_ror, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_spec_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2, top = "Specificity plots for Setting 1 (\U03B2 = 100, p = 0.1)")

spec_plot_file <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_beta_fixed_p/beta100_p0_1/spec.png"
combined_spec_plot
ggsave(filename = spec_plot_file, plot = combined_spec_plot)

## overall accuracy plots
#confidence thresholds
mean_acc_conf <- as.numeric(conf_results_p_0_1_beta100[5,])

#prr thresholds
mean_acc_prr <- as.numeric(prr_results_p_0_1_beta100[5,])

#rr thresholds
mean_acc_rr <- as.numeric(rr_results_p_0_1_beta100[5,])

#ror thresholds
mean_acc_ror <- as.numeric(ror_results_p_0_1_beta100[5,])

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_acc_conf, group=1)) + 
  geom_point(aes(x=conf_thresh, y=mean_acc_conf, group=1)) + 
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_acc_prr, group=1)) + 
  geom_point(aes(x=prr_thresh, y=mean_acc_prr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_acc_rr, group=1)) + 
  geom_point(aes(x=rr_thresh, y=mean_acc_rr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_acc_ror, group=1)) + 
  geom_point(aes(x=ror_thresh, y=mean_acc_ror, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_acc_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2, top = "Overall Accuracy plots for Setting 1 (\U03B2 = 100, p = 0.1)")

acc_plot_file <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_beta_fixed_p/beta100_p0_1/acc.png"
combined_acc_plot
ggsave(filename = acc_plot_file, plot = combined_acc_plot)
```

```{r b_100_p_0_3}
conf_thresh <- as.factor(c(0.4,0.5,0.6,0.7))
prr_thresh <- as.factor(c(1,1.2,1.5,2))
rr_thresh <- as.factor(c(1,1.2,1.5,2))
ror_thresh <- as.factor(c(1,1.2,1.5,2))

#sensitivity plots
#confidence thresholds
mean_sens_conf <- as.numeric(conf_results_p_0_3_beta100[1,])

#prr thresholds
mean_sens_prr <- as.numeric(prr_results_p_0_3_beta100[1,])

#rr thresholds
mean_sens_rr <- as.numeric(rr_results_p_0_3_beta100[1,])

#ror thresholds
mean_sens_ror <- as.numeric(ror_results_p_0_3_beta100[1,])

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_sens_conf, group=1)) + 
  geom_point(aes(x=conf_thresh, y=mean_sens_conf, group=1)) + 
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_sens_prr, group=1)) + 
  geom_point(aes(x=prr_thresh, y=mean_sens_prr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_sens_rr, group=1)) + 
  geom_point(aes(x=rr_thresh, y=mean_sens_rr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_sens_ror, group=1)) + 
  geom_point(aes(x=ror_thresh, y=mean_sens_ror, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_sens_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2, top = "Sensitivity plots for Setting 1 (\U03B2 = 100, p = 0.3)")

#final combined Sensitivity plot with common legend
#combined_sens_plot <- grid.arrange(combined_plot, nrow=2, heights=c(8.5,2), top = "Sensitivity plots for 1 drug and 3 AEs setting - beta = 1, p = 0.1")
sens_plot_file <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_beta_fixed_p/beta100_p0_3/sens.png"
combined_sens_plot
ggsave(filename = sens_plot_file, plot = combined_sens_plot)

## specificity plots
#confidence thresholds
mean_spec_conf <- as.numeric(conf_results_p_0_3_beta100[2,])

#prr thresholds
mean_spec_prr <- as.numeric(prr_results_p_0_3_beta100[2,])

#rr thresholds
mean_spec_rr <- as.numeric(rr_results_p_0_3_beta100[2,])

#ror thresholds
mean_spec_ror <- as.numeric(ror_results_p_0_3_beta100[2,])

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_spec_conf, group=1)) + 
  geom_point(aes(x=conf_thresh, y=mean_spec_conf, group=1)) + 
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_spec_prr, group=1)) + 
  geom_point(aes(x=prr_thresh, y=mean_spec_prr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_spec_rr, group=1)) + 
  geom_point(aes(x=rr_thresh, y=mean_spec_rr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_spec_ror, group=1)) + 
  geom_point(aes(x=ror_thresh, y=mean_spec_ror, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_spec_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2, top = "Specificity plots for Setting 1 (\U03B2 = 100, p = 0.3)")

spec_plot_file <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_beta_fixed_p/beta100_p0_3/spec.png"
combined_spec_plot
ggsave(filename = spec_plot_file, plot = combined_spec_plot)

## overall accuracy plots
#confidence thresholds
mean_acc_conf <- as.numeric(conf_results_p_0_3_beta100[5,])

#prr thresholds
mean_acc_prr <- as.numeric(prr_results_p_0_3_beta100[5,])

#rr thresholds
mean_acc_rr <- as.numeric(rr_results_p_0_3_beta100[5,])

#ror thresholds
mean_acc_ror <- as.numeric(ror_results_p_0_3_beta100[5,])

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_acc_conf, group=1)) + 
  geom_point(aes(x=conf_thresh, y=mean_acc_conf, group=1)) + 
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_acc_prr, group=1)) + 
  geom_point(aes(x=prr_thresh, y=mean_acc_prr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_acc_rr, group=1)) + 
  geom_point(aes(x=rr_thresh, y=mean_acc_rr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_acc_ror, group=1)) + 
  geom_point(aes(x=ror_thresh, y=mean_acc_ror, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_acc_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2, top = "Overall Accuracy plots for Setting 1 (\U03B2 = 100, p = 0.3)")

acc_plot_file <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_beta_fixed_p/beta100_p0_3/acc.png"
combined_acc_plot
ggsave(filename = acc_plot_file, plot = combined_acc_plot)
```

```{r b_100_p_0_5}
conf_thresh <- as.factor(c(0.4,0.5,0.6,0.7))
prr_thresh <- as.factor(c(1,1.2,1.5,2))
rr_thresh <- as.factor(c(1,1.2,1.5,2))
ror_thresh <- as.factor(c(1,1.2,1.5,2))

#sensitivity plots
#confidence thresholds
mean_sens_conf <- as.numeric(conf_results_p_0_5_beta100[1,])

#prr thresholds
mean_sens_prr <- as.numeric(prr_results_p_0_5_beta100[1,])

#rr thresholds
mean_sens_rr <- as.numeric(rr_results_p_0_5_beta100[1,])

#ror thresholds
mean_sens_ror <- as.numeric(ror_results_p_0_5_beta100[1,])

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_sens_conf, group=1)) + 
  geom_point(aes(x=conf_thresh, y=mean_sens_conf, group=1)) + 
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_sens_prr, group=1)) + 
  geom_point(aes(x=prr_thresh, y=mean_sens_prr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_sens_rr, group=1)) + 
  geom_point(aes(x=rr_thresh, y=mean_sens_rr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_sens_ror, group=1)) + 
  geom_point(aes(x=ror_thresh, y=mean_sens_ror, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_sens_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2, top = "Sensitivity plots for Setting 1 (\U03B2 = 100, p = 0.5)")

#final combined Sensitivity plot with common legend
#combined_sens_plot <- grid.arrange(combined_plot, nrow=2, heights=c(8.5,2), top = "Sensitivity plots for 1 drug and 3 AEs setting - beta = 1, p = 0.1")
sens_plot_file <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_beta_fixed_p/beta100_p0_5/sens.png"
combined_sens_plot
ggsave(filename = sens_plot_file, plot = combined_sens_plot)

## specificity plots
#confidence thresholds
mean_spec_conf <- as.numeric(conf_results_p_0_5_beta50[2,])

#prr thresholds
mean_spec_prr <- as.numeric(prr_results_p_0_5_beta50[2,])

#rr thresholds
mean_spec_rr <- as.numeric(rr_results_p_0_5_beta50[2,])

#ror thresholds
mean_spec_ror <- as.numeric(ror_results_p_0_5_beta50[2,])

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_spec_conf, group=1)) + 
  geom_point(aes(x=conf_thresh, y=mean_spec_conf, group=1)) + 
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_spec_prr, group=1)) + 
  geom_point(aes(x=prr_thresh, y=mean_spec_prr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_spec_rr, group=1)) + 
  geom_point(aes(x=rr_thresh, y=mean_spec_rr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_spec_ror, group=1)) + 
  geom_point(aes(x=ror_thresh, y=mean_spec_ror, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_spec_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2, top = "Specificity plots for Setting 1 (\U03B2 = 100, p = 0.5)")

spec_plot_file <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_beta_fixed_p/beta100_p0_5/spec.png"
combined_spec_plot
ggsave(filename = spec_plot_file, plot = combined_spec_plot)

## overall accuracy plots
#confidence thresholds
mean_acc_conf <- as.numeric(conf_results_p_0_5_beta100[5,])

#prr thresholds
mean_acc_prr <- as.numeric(prr_results_p_0_5_beta100[5,])

#rr thresholds
mean_acc_rr <- as.numeric(rr_results_p_0_5_beta100[5,])

#ror thresholds
mean_acc_ror <- as.numeric(ror_results_p_0_5_beta100[5,])

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_acc_conf, group=1)) + 
  geom_point(aes(x=conf_thresh, y=mean_acc_conf, group=1)) + 
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_acc_prr, group=1)) + 
  geom_point(aes(x=prr_thresh, y=mean_acc_prr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_acc_rr, group=1)) + 
  geom_point(aes(x=rr_thresh, y=mean_acc_rr, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_acc_ror, group=1)) + 
  geom_point(aes(x=ror_thresh, y=mean_acc_ror, group=1)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  #scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_acc_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2, top = "Overall Accuracy plots for Setting 1 (\U03B2 = 100, p = 0.5)")

acc_plot_file <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_beta_fixed_p/beta100_p0_5/acc.png"
combined_acc_plot
ggsave(filename = acc_plot_file, plot = combined_acc_plot)
```

## fixed beta
```{r b_1}
conf_thresh <- as.factor(rep(c(0.4,0.5,0.6,0.7), 3))
prr_thresh <- as.factor(rep(c(1,1.2,1.5,2), 3))
rr_thresh <- as.factor(rep(c(1,1.2,1.5,2), 3))
ror_thresh <- as.factor(rep(c(1,1.2,1.5,2), 3))
p <- as.factor(c(rep(0.1,4), rep(0.3, 4), rep(0.5, 4)))

#sensitivity plots
#confidence thresholds
mean_sens_conf <- as.numeric(c(conf_results_p_0_1_beta1[1,], conf_results_p_0_3_beta1[1,], conf_results_p_0_5_beta1[1,]))

#prr thresholds
mean_sens_prr <- as.numeric(c(prr_results_p_0_1_beta1[1,], prr_results_p_0_3_beta1[1,], prr_results_p_0_5_beta1[1,]))

#rr thresholds
mean_sens_rr <- as.numeric(c(rr_results_p_0_1_beta1[1,], rr_results_p_0_3_beta1[1,], rr_results_p_0_5_beta1[1,]))

#ror thresholds
mean_sens_ror <- as.numeric(c(ror_results_p_0_1_beta1[1,], ror_results_p_0_3_beta1[1,], ror_results_p_0_5_beta1[1,]))

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_sens_conf, group=p, color = p)) + 
  geom_point(aes(x=conf_thresh, y=mean_sens_conf, color = p)) + 
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_sens_prr, group=p, color = p)) + 
  geom_point(aes(x=prr_thresh, y=mean_sens_prr, color = p)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_sens_rr, group=p, color = p)) + 
  geom_point(aes(x=rr_thresh, y=mean_sens_rr, color = p)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_sens_ror, group=p, color = p)) + 
  geom_point(aes(x=ror_thresh, y=mean_sens_ror, color = p)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2)

g1_legend <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_sens_conf, group=p, color=p)) + 
  geom_point(aes(x=conf_thresh, y=mean_sens_conf, color=p)) + 
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18), name=greeks("beta")) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99"), name="p") +
  labs(y="Mean Sensitivity", x="Confidence thresholds") + 
  #scale_color_discrete(name=greeks("rho")) +
  #scale_shape_discrete(name=greeks("beta")) +
  #scale_linetype_discrete(name=greeks("beta")) +
  theme(legend.position = "bottom", axis.text=element_text(size=10),
        axis.title=element_text(size=8), legend.title = element_text(size=10, face="bold"), 
        legend.text = element_text(size=8))

#function to extract legend from plot
get_only_legend <- function(plot) {
  plot_table <- ggplot_gtable(ggplot_build(plot))
  legend_plot <- which(sapply(plot_table$grobs, function(x) x$name) == "guide-box")
  legend <- plot_table$grobs[[legend_plot]]
  return(legend)
}

#extract legend from g1 using above function
legend <- get_only_legend(g1_legend)

#final combined Sensitivity plot with common legend
combined_sens_plot <- grid.arrange(combined_plot, legend, nrow=2, heights=c(8.5,2), top = "Sensitivity plots for Setting 1 (\U03B2 = 1)")
sens_plot_file <- "/Users/reetikasarkar/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_beta/beta1/sens.png"
combined_sens_plot
ggsave(filename = sens_plot_file, plot = combined_sens_plot)

## specificity plots
#confidence thresholds
mean_spec_conf <- as.numeric(c(conf_results_p_0_1_beta1[2,], conf_results_p_0_3_beta1[2,], conf_results_p_0_5_beta1[2,]))

#prr thresholds
mean_spec_prr <- as.numeric(c(prr_results_p_0_1_beta1[2,], prr_results_p_0_3_beta1[2,], prr_results_p_0_5_beta1[2,]))

#rr thresholds
mean_spec_rr <- as.numeric(c(rr_results_p_0_1_beta1[2,], rr_results_p_0_3_beta1[2,], rr_results_p_0_5_beta1[2,]))

#ror thresholds
mean_spec_ror <- as.numeric(c(ror_results_p_0_1_beta1[2,], ror_results_p_0_3_beta1[2,], ror_results_p_0_5_beta1[2,]))

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_spec_conf, group=p, color=p)) + 
  geom_point(aes(x=conf_thresh, y=mean_spec_conf, group=p, color=p)) + 
  ylim(0.7,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_spec_prr, group=p, color=p)) + 
  geom_point(aes(x=prr_thresh, y=mean_spec_prr, group=p, color=p)) +
  ylim(0.7,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_spec_rr, group=p, color=p)) + 
  geom_point(aes(x=rr_thresh, y=mean_spec_rr, group=p, color=p)) +
  ylim(0.7,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_spec_ror, group=p, color=p)) + 
  geom_point(aes(x=ror_thresh, y=mean_spec_ror, group=p, color=p)) +
  ylim(0.7,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2)

g1_legend <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_spec_conf, group=p, color=p)) + 
  geom_point(aes(x=conf_thresh, y=mean_spec_conf, color=p)) + 
  ylim(0.7,1) +
  #scale_shape_manual(values = c(15,16,17,18), name=greeks("beta")) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99"), name="p") +
  labs(y="Mean Specificity", x="Confidence thresholds") + 
  #scale_color_discrete(name=greeks("rho")) +
  #scale_shape_discrete(name=greeks("beta")) +
  #scale_linetype_discrete(name=greeks("beta")) +
  theme(legend.position = "bottom", axis.text=element_text(size=10), axis.title=element_text(size=8), legend.title = element_text(size=10, face="bold"), legend.text = element_text(size=8))

#function to extract legend from plot
get_only_legend <- function(plot) {
  plot_table <- ggplot_gtable(ggplot_build(plot))
  legend_plot <- which(sapply(plot_table$grobs, function(x) x$name) == "guide-box")
  legend <- plot_table$grobs[[legend_plot]]
  return(legend)
}

#extract legend from g1 using above function
legend <- get_only_legend(g1_legend)

combined_spec_plot <- grid.arrange(combined_plot, legend, nrow=2, heights=c(8.5,2), top = "Specificity plots for Setting 1 (\U03B2 = 1)")

spec_plot_file <- "/Users/reetikasarkar/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_beta/beta1/spec.png"
combined_spec_plot
ggsave(filename = spec_plot_file, plot = combined_spec_plot)

## overall accuracy plots
#confidence thresholds
mean_acc_conf <- as.numeric(c(conf_results_p_0_1_beta1[5,], conf_results_p_0_3_beta1[5,], conf_results_p_0_5_beta1[5,]))

#prr thresholds
mean_acc_prr <- as.numeric(c(prr_results_p_0_1_beta1[5,], prr_results_p_0_3_beta1[5,], prr_results_p_0_5_beta1[5,]))

#rr thresholds
mean_acc_rr <- as.numeric(c(rr_results_p_0_1_beta1[5,], rr_results_p_0_3_beta1[5,], rr_results_p_0_5_beta1[5,]))

#ror thresholds
mean_acc_ror <- as.numeric(c(ror_results_p_0_1_beta1[5,], ror_results_p_0_3_beta1[5,], ror_results_p_0_5_beta1[5,]))

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_acc_conf, group=p, color=p)) + 
  geom_point(aes(x=conf_thresh, y=mean_acc_conf, color=p)) + 
  ylim(0.7,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_acc_prr, group=p, color=p)) + 
  geom_point(aes(x=prr_thresh, y=mean_acc_prr, color=p)) +
  ylim(0.7,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_acc_rr, group=p, color=p)) + 
  geom_point(aes(x=rr_thresh, y=mean_acc_rr, color=p)) +
  ylim(0.7,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_acc_ror, group=p, color=p)) + 
  geom_point(aes(x=ror_thresh, y=mean_acc_ror, color=p)) +
  ylim(0.7,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2)

g1_legend <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_spec_conf, group=p, color=p)) + 
  geom_point(aes(x=conf_thresh, y=mean_spec_conf, color=p)) + 
  ylim(0.7,1) +
  #scale_shape_manual(values = c(15,16,17,18), name=greeks("beta")) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99"), name="p") +
  labs(y="Mean Specificity", x="Confidence thresholds") + 
  #scale_color_discrete(name=greeks("rho")) +
  #scale_shape_discrete(name=greeks("beta")) +
  #scale_linetype_discrete(name=greeks("beta")) +
  theme(legend.position = "bottom", axis.text=element_text(size=10), axis.title=element_text(size=8), legend.title = element_text(size=10, face="bold"), legend.text = element_text(size=8))

#function to extract legend from plot
get_only_legend <- function(plot) {
  plot_table <- ggplot_gtable(ggplot_build(plot))
  legend_plot <- which(sapply(plot_table$grobs, function(x) x$name) == "guide-box")
  legend <- plot_table$grobs[[legend_plot]]
  return(legend)
}

#extract legend from g1 using above function
legend <- get_only_legend(g1_legend)

combined_acc_plot <- grid.arrange(combined_plot, legend, nrow=2, heights=c(8.5,2), top = "Overall Accuracy plots for Setting 1 (\U03B2 = 1)")

acc_plot_file <- "/Users/reetikasarkar/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_beta/beta1/acc.png"
combined_acc_plot
ggsave(filename = acc_plot_file, plot = combined_acc_plot)
```

```{r b_10}
conf_thresh <- as.factor(rep(c(0.4,0.5,0.6,0.7), 3))
prr_thresh <- as.factor(rep(c(1,1.2,1.5,2), 3))
rr_thresh <- as.factor(rep(c(1,1.2,1.5,2), 3))
ror_thresh <- as.factor(rep(c(1,1.2,1.5,2), 3))
p <- as.factor(c(rep(0.1,4), rep(0.3, 4), rep(0.5, 4)))

#sensitivity plots
#confidence thresholds
mean_sens_conf <- as.numeric(c(conf_results_p_0_1_beta10[1,], conf_results_p_0_3_beta10[1,], conf_results_p_0_5_beta10[1,]))

#prr thresholds
mean_sens_prr <- as.numeric(c(prr_results_p_0_1_beta10[1,], prr_results_p_0_3_beta10[1,], prr_results_p_0_5_beta10[1,]))

#rr thresholds
mean_sens_rr <- as.numeric(c(rr_results_p_0_1_beta10[1,], rr_results_p_0_3_beta10[1,], rr_results_p_0_5_beta10[1,]))

#ror thresholds
mean_sens_ror <- as.numeric(c(ror_results_p_0_1_beta10[1,], ror_results_p_0_3_beta10[1,], ror_results_p_0_5_beta10[1,]))

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_sens_conf, group=p, color = p)) + 
  geom_point(aes(x=conf_thresh, y=mean_sens_conf, color = p)) + 
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_sens_prr, group=p, color = p)) + 
  geom_point(aes(x=prr_thresh, y=mean_sens_prr, color = p)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_sens_rr, group=p, color = p)) + 
  geom_point(aes(x=rr_thresh, y=mean_sens_rr, color = p)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_sens_ror, group=p, color = p)) + 
  geom_point(aes(x=ror_thresh, y=mean_sens_ror, color = p)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2)

g1_legend <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_sens_conf, group=p, color=p)) + 
  geom_point(aes(x=conf_thresh, y=mean_sens_conf, color=p)) + 
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18), name=greeks("beta")) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99"), name="p") +
  labs(y="Mean Sensitivity", x="Confidence thresholds") + 
  #scale_color_discrete(name=greeks("rho")) +
  #scale_shape_discrete(name=greeks("beta")) +
  #scale_linetype_discrete(name=greeks("beta")) +
  theme(legend.position = "bottom", axis.text=element_text(size=10),
        axis.title=element_text(size=8), legend.title = element_text(size=10, face="bold"), 
        legend.text = element_text(size=8))

#function to extract legend from plot
get_only_legend <- function(plot) {
  plot_table <- ggplot_gtable(ggplot_build(plot))
  legend_plot <- which(sapply(plot_table$grobs, function(x) x$name) == "guide-box")
  legend <- plot_table$grobs[[legend_plot]]
  return(legend)
}

#extract legend from g1 using above function
legend <- get_only_legend(g1_legend)

#final combined Sensitivity plot with common legend
combined_sens_plot <- grid.arrange(combined_plot, legend, nrow=2, heights=c(8.5,2), top = "Sensitivity plots for Setting 1 (\U03B2 = 10)")
sens_plot_file <- "/Users/reetikasarkar/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_beta/beta10/sens.png"
combined_sens_plot
ggsave(filename = sens_plot_file, plot = combined_sens_plot)

## specificity plots
#confidence thresholds
mean_spec_conf <- as.numeric(c(conf_results_p_0_1_beta10[2,], conf_results_p_0_3_beta10[2,], conf_results_p_0_5_beta10[2,]))

#prr thresholds
mean_spec_prr <- as.numeric(c(prr_results_p_0_1_beta10[2,], prr_results_p_0_3_beta10[2,], prr_results_p_0_5_beta10[2,]))

#rr thresholds
mean_spec_rr <- as.numeric(c(rr_results_p_0_1_beta10[2,], rr_results_p_0_3_beta10[2,], rr_results_p_0_5_beta10[2,]))

#ror thresholds
mean_spec_ror <- as.numeric(c(ror_results_p_0_1_beta10[2,], ror_results_p_0_3_beta10[2,], ror_results_p_0_5_beta10[2,]))

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_spec_conf, group=p, color=p)) + 
  geom_point(aes(x=conf_thresh, y=mean_spec_conf, group=p, color=p)) + 
  ylim(0.5,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_spec_prr, group=p, color=p)) + 
  geom_point(aes(x=prr_thresh, y=mean_spec_prr, group=p, color=p)) +
  ylim(0.5,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_spec_rr, group=p, color=p)) + 
  geom_point(aes(x=rr_thresh, y=mean_spec_rr, group=p, color=p)) +
  ylim(0.5,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_spec_ror, group=p, color=p)) + 
  geom_point(aes(x=ror_thresh, y=mean_spec_ror, group=p, color=p)) +
  ylim(0.5,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2)

g1_legend <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_spec_conf, group=p, color=p)) + 
  geom_point(aes(x=conf_thresh, y=mean_spec_conf, color=p)) + 
  ylim(0.5,1) +
  #scale_shape_manual(values = c(15,16,17,18), name=greeks("beta")) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99"), name="p") +
  labs(y="Mean Specificity", x="Confidence thresholds") + 
  #scale_color_discrete(name=greeks("rho")) +
  #scale_shape_discrete(name=greeks("beta")) +
  #scale_linetype_discrete(name=greeks("beta")) +
  theme(legend.position = "bottom", axis.text=element_text(size=10), axis.title=element_text(size=8), legend.title = element_text(size=10, face="bold"), legend.text = element_text(size=8))

#function to extract legend from plot
get_only_legend <- function(plot) {
  plot_table <- ggplot_gtable(ggplot_build(plot))
  legend_plot <- which(sapply(plot_table$grobs, function(x) x$name) == "guide-box")
  legend <- plot_table$grobs[[legend_plot]]
  return(legend)
}

#extract legend from g1 using above function
legend <- get_only_legend(g1_legend)

combined_spec_plot <- grid.arrange(combined_plot, legend, nrow=2, heights=c(8.5,2), top = "Specificity plots for Setting 1 (\U03B2 = 10)")

spec_plot_file <- "/Users/reetikasarkar/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_beta/beta10/spec.png"
combined_spec_plot
ggsave(filename = spec_plot_file, plot = combined_spec_plot)

## overall accuracy plots
#confidence thresholds
mean_acc_conf <- as.numeric(c(conf_results_p_0_1_beta10[5,], conf_results_p_0_3_beta10[5,], conf_results_p_0_5_beta10[5,]))

#prr thresholds
mean_acc_prr <- as.numeric(c(prr_results_p_0_1_beta10[5,], prr_results_p_0_3_beta10[5,], prr_results_p_0_5_beta10[5,]))

#rr thresholds
mean_acc_rr <- as.numeric(c(rr_results_p_0_1_beta10[5,], rr_results_p_0_3_beta10[5,], rr_results_p_0_5_beta10[5,]))

#ror thresholds
mean_acc_ror <- as.numeric(c(ror_results_p_0_1_beta10[5,], ror_results_p_0_3_beta10[5,], ror_results_p_0_5_beta10[5,]))

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_acc_conf, group=p, color=p)) + 
  geom_point(aes(x=conf_thresh, y=mean_acc_conf, color=p)) + 
  ylim(0.6,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_acc_prr, group=p, color=p)) + 
  geom_point(aes(x=prr_thresh, y=mean_acc_prr, color=p)) +
  ylim(0.6,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_acc_rr, group=p, color=p)) + 
  geom_point(aes(x=rr_thresh, y=mean_acc_rr, color=p)) +
  ylim(0.6,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_acc_ror, group=p, color=p)) + 
  geom_point(aes(x=ror_thresh, y=mean_acc_ror, color=p)) +
  ylim(0.6,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2)

g1_legend <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_spec_conf, group=p, color=p)) + 
  geom_point(aes(x=conf_thresh, y=mean_spec_conf, color=p)) + 
  ylim(0.6,1) +
  #scale_shape_manual(values = c(15,16,17,18), name=greeks("beta")) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99"), name="p") +
  labs(y="Mean Specificity", x="Confidence thresholds") + 
  #scale_color_discrete(name=greeks("rho")) +
  #scale_shape_discrete(name=greeks("beta")) +
  #scale_linetype_discrete(name=greeks("beta")) +
  theme(legend.position = "bottom", axis.text=element_text(size=10), axis.title=element_text(size=8), legend.title = element_text(size=10, face="bold"), legend.text = element_text(size=8))

#function to extract legend from plot
get_only_legend <- function(plot) {
  plot_table <- ggplot_gtable(ggplot_build(plot))
  legend_plot <- which(sapply(plot_table$grobs, function(x) x$name) == "guide-box")
  legend <- plot_table$grobs[[legend_plot]]
  return(legend)
}

#extract legend from g1 using above function
legend <- get_only_legend(g1_legend)

combined_acc_plot <- grid.arrange(combined_plot, legend, nrow=2, heights=c(8.5,2), top = "Overall Accuracy plots for Setting 1 (\U03B2 = 10)")

acc_plot_file <- "/Users/reetikasarkar/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_beta/beta10/acc.png"
combined_acc_plot
ggsave(filename = acc_plot_file, plot = combined_acc_plot)
```

```{r b_50}
conf_thresh <- as.factor(rep(c(0.4,0.5,0.6,0.7), 3))
prr_thresh <- as.factor(rep(c(1,1.2,1.5,2), 3))
rr_thresh <- as.factor(rep(c(1,1.2,1.5,2), 3))
ror_thresh <- as.factor(rep(c(1,1.2,1.5,2), 3))
p <- as.factor(c(rep(0.1,4), rep(0.3, 4), rep(0.5, 4)))

#sensitivity plots
#confidence thresholds
mean_sens_conf <- as.numeric(c(conf_results_p_0_1_beta50[1,], conf_results_p_0_3_beta50[1,], conf_results_p_0_5_beta50[1,]))

#prr thresholds
mean_sens_prr <- as.numeric(c(prr_results_p_0_1_beta50[1,], prr_results_p_0_3_beta50[1,], prr_results_p_0_5_beta50[1,]))

#rr thresholds
mean_sens_rr <- as.numeric(c(rr_results_p_0_1_beta50[1,], rr_results_p_0_3_beta50[1,], rr_results_p_0_5_beta50[1,]))

#ror thresholds
mean_sens_ror <- as.numeric(c(ror_results_p_0_1_beta50[1,], ror_results_p_0_3_beta50[1,], ror_results_p_0_5_beta50[1,]))

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_sens_conf, group=p, color = p)) + 
  geom_point(aes(x=conf_thresh, y=mean_sens_conf, color = p)) + 
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_sens_prr, group=p, color = p)) + 
  geom_point(aes(x=prr_thresh, y=mean_sens_prr, color = p)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_sens_rr, group=p, color = p)) + 
  geom_point(aes(x=rr_thresh, y=mean_sens_rr, color = p)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_sens_ror, group=p, color = p)) + 
  geom_point(aes(x=ror_thresh, y=mean_sens_ror, color = p)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2)

g1_legend <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_sens_conf, group=p, color=p)) + 
  geom_point(aes(x=conf_thresh, y=mean_sens_conf, color=p)) + 
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18), name=greeks("beta")) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99"), name="p") +
  labs(y="Mean Sensitivity", x="Confidence thresholds") + 
  #scale_color_discrete(name=greeks("rho")) +
  #scale_shape_discrete(name=greeks("beta")) +
  #scale_linetype_discrete(name=greeks("beta")) +
  theme(legend.position = "bottom", axis.text=element_text(size=10),
        axis.title=element_text(size=8), legend.title = element_text(size=10, face="bold"), 
        legend.text = element_text(size=8))

#function to extract legend from plot
get_only_legend <- function(plot) {
  plot_table <- ggplot_gtable(ggplot_build(plot))
  legend_plot <- which(sapply(plot_table$grobs, function(x) x$name) == "guide-box")
  legend <- plot_table$grobs[[legend_plot]]
  return(legend)
}

#extract legend from g1 using above function
legend <- get_only_legend(g1_legend)

#final combined Sensitivity plot with common legend
combined_sens_plot <- grid.arrange(combined_plot, legend, nrow=2, heights=c(8.5,2), top = "Sensitivity plots for Setting 1 (\U03B2 = 50)")
sens_plot_file <- "/Users/reetikasarkar/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_beta/beta50/sens.png"
combined_sens_plot
ggsave(filename = sens_plot_file, plot = combined_sens_plot)

## specificity plots
#confidence thresholds
mean_spec_conf <- as.numeric(c(conf_results_p_0_1_beta50[2,], conf_results_p_0_3_beta50[2,], conf_results_p_0_5_beta50[2,]))

#prr thresholds
mean_spec_prr <- as.numeric(c(prr_results_p_0_1_beta50[2,], prr_results_p_0_3_beta50[2,], prr_results_p_0_5_beta50[2,]))

#rr thresholds
mean_spec_rr <- as.numeric(c(rr_results_p_0_1_beta50[2,], rr_results_p_0_3_beta50[2,], rr_results_p_0_5_beta50[2,]))

#ror thresholds
mean_spec_ror <- as.numeric(c(ror_results_p_0_1_beta50[2,], ror_results_p_0_3_beta50[2,], ror_results_p_0_5_beta50[2,]))

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_spec_conf, group=p, color=p)) + 
  geom_point(aes(x=conf_thresh, y=mean_spec_conf, group=p, color=p)) + 
  ylim(0.5,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_spec_prr, group=p, color=p)) + 
  geom_point(aes(x=prr_thresh, y=mean_spec_prr, group=p, color=p)) +
  ylim(0.5,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_spec_rr, group=p, color=p)) + 
  geom_point(aes(x=rr_thresh, y=mean_spec_rr, group=p, color=p)) +
  ylim(0.5,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_spec_ror, group=p, color=p)) + 
  geom_point(aes(x=ror_thresh, y=mean_spec_ror, group=p, color=p)) +
  ylim(0.5,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2)

g1_legend <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_spec_conf, group=p, color=p)) + 
  geom_point(aes(x=conf_thresh, y=mean_spec_conf, color=p)) + 
  ylim(0.5,1) +
  #scale_shape_manual(values = c(15,16,17,18), name=greeks("beta")) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99"), name="p") +
  labs(y="Mean Specificity", x="Confidence thresholds") + 
  #scale_color_discrete(name=greeks("rho")) +
  #scale_shape_discrete(name=greeks("beta")) +
  #scale_linetype_discrete(name=greeks("beta")) +
  theme(legend.position = "bottom", axis.text=element_text(size=10), axis.title=element_text(size=8), legend.title = element_text(size=10, face="bold"), legend.text = element_text(size=8))

#function to extract legend from plot
get_only_legend <- function(plot) {
  plot_table <- ggplot_gtable(ggplot_build(plot))
  legend_plot <- which(sapply(plot_table$grobs, function(x) x$name) == "guide-box")
  legend <- plot_table$grobs[[legend_plot]]
  return(legend)
}

#extract legend from g1 using above function
legend <- get_only_legend(g1_legend)

combined_spec_plot <- grid.arrange(combined_plot, legend, nrow=2, heights=c(8.5,2), top = "Specificity plots for Setting 1 (\U03B2 = 50)")

spec_plot_file <- "/Users/reetikasarkar/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_beta/beta50/spec.png"
combined_spec_plot
ggsave(filename = spec_plot_file, plot = combined_spec_plot)

## overall accuracy plots
#confidence thresholds
mean_acc_conf <- as.numeric(c(conf_results_p_0_1_beta50[5,], conf_results_p_0_3_beta50[5,], conf_results_p_0_5_beta50[5,]))

#prr thresholds
mean_acc_prr <- as.numeric(c(prr_results_p_0_1_beta50[5,], prr_results_p_0_3_beta50[5,], prr_results_p_0_5_beta50[5,]))

#rr thresholds
mean_acc_rr <- as.numeric(c(rr_results_p_0_1_beta50[5,], rr_results_p_0_3_beta50[5,], rr_results_p_0_5_beta50[5,]))

#ror thresholds
mean_acc_ror <- as.numeric(c(ror_results_p_0_1_beta50[5,], ror_results_p_0_3_beta50[5,], ror_results_p_0_5_beta50[5,]))

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_acc_conf, group=p, color=p)) + 
  geom_point(aes(x=conf_thresh, y=mean_acc_conf, color=p)) + 
  ylim(0.6,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_acc_prr, group=p, color=p)) + 
  geom_point(aes(x=prr_thresh, y=mean_acc_prr, color=p)) +
  ylim(0.6,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_acc_rr, group=p, color=p)) + 
  geom_point(aes(x=rr_thresh, y=mean_acc_rr, color=p)) +
  ylim(0.6,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_acc_ror, group=p, color=p)) + 
  geom_point(aes(x=ror_thresh, y=mean_acc_ror, color=p)) +
  ylim(0.6,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2)

g1_legend <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_spec_conf, group=p, color=p)) + 
  geom_point(aes(x=conf_thresh, y=mean_spec_conf, color=p)) + 
  ylim(0.6,1) +
  #scale_shape_manual(values = c(15,16,17,18), name=greeks("beta")) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99"), name="p") +
  labs(y="Mean Specificity", x="Confidence thresholds") + 
  #scale_color_discrete(name=greeks("rho")) +
  #scale_shape_discrete(name=greeks("beta")) +
  #scale_linetype_discrete(name=greeks("beta")) +
  theme(legend.position = "bottom", axis.text=element_text(size=10), axis.title=element_text(size=8), legend.title = element_text(size=10, face="bold"), legend.text = element_text(size=8))

#function to extract legend from plot
get_only_legend <- function(plot) {
  plot_table <- ggplot_gtable(ggplot_build(plot))
  legend_plot <- which(sapply(plot_table$grobs, function(x) x$name) == "guide-box")
  legend <- plot_table$grobs[[legend_plot]]
  return(legend)
}

#extract legend from g1 using above function
legend <- get_only_legend(g1_legend)

combined_acc_plot <- grid.arrange(combined_plot, legend, nrow=2, heights=c(8.5,2), top = "Overall Accuracy plots for Setting 1 (\U03B2 = 50)")

acc_plot_file <- "/Users/reetikasarkar/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_beta/beta50/acc.png"
combined_acc_plot
ggsave(filename = acc_plot_file, plot = combined_acc_plot)
```

```{r b_100}
conf_thresh <- as.factor(rep(c(0.4,0.5,0.6,0.7), 3))
prr_thresh <- as.factor(rep(c(1,1.2,1.5,2), 3))
rr_thresh <- as.factor(rep(c(1,1.2,1.5,2), 3))
ror_thresh <- as.factor(rep(c(1,1.2,1.5,2), 3))
p <- as.factor(c(rep(0.1,4), rep(0.3, 4), rep(0.5, 4)))

#sensitivity plots
#confidence thresholds
mean_sens_conf <- as.numeric(c(conf_results_p_0_1_beta100[1,], conf_results_p_0_3_beta100[1,], conf_results_p_0_5_beta100[1,]))

#prr thresholds
mean_sens_prr <- as.numeric(c(prr_results_p_0_1_beta100[1,], prr_results_p_0_3_beta100[1,], prr_results_p_0_5_beta100[1,]))

#rr thresholds
mean_sens_rr <- as.numeric(c(rr_results_p_0_1_beta100[1,], rr_results_p_0_3_beta100[1,], rr_results_p_0_5_beta100[1,]))

#ror thresholds
mean_sens_ror <- as.numeric(c(ror_results_p_0_1_beta100[1,], ror_results_p_0_3_beta100[1,], ror_results_p_0_5_beta100[1,]))

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_sens_conf, group=p, color = p)) + 
  geom_point(aes(x=conf_thresh, y=mean_sens_conf, color = p)) + 
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_sens_prr, group=p, color = p)) + 
  geom_point(aes(x=prr_thresh, y=mean_sens_prr, color = p)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_sens_rr, group=p, color = p)) + 
  geom_point(aes(x=rr_thresh, y=mean_sens_rr, color = p)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_sens_ror, group=p, color = p)) + 
  geom_point(aes(x=ror_thresh, y=mean_sens_ror, color = p)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2)

g1_legend <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_sens_conf, group=p, color=p)) + 
  geom_point(aes(x=conf_thresh, y=mean_sens_conf, color=p)) + 
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18), name=greeks("beta")) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99"), name="p") +
  labs(y="Mean Sensitivity", x="Confidence thresholds") + 
  #scale_color_discrete(name=greeks("rho")) +
  #scale_shape_discrete(name=greeks("beta")) +
  #scale_linetype_discrete(name=greeks("beta")) +
  theme(legend.position = "bottom", axis.text=element_text(size=10),
        axis.title=element_text(size=8), legend.title = element_text(size=10, face="bold"), 
        legend.text = element_text(size=8))

#function to extract legend from plot
get_only_legend <- function(plot) {
  plot_table <- ggplot_gtable(ggplot_build(plot))
  legend_plot <- which(sapply(plot_table$grobs, function(x) x$name) == "guide-box")
  legend <- plot_table$grobs[[legend_plot]]
  return(legend)
}

#extract legend from g1 using above function
legend <- get_only_legend(g1_legend)

#final combined Sensitivity plot with common legend
combined_sens_plot <- grid.arrange(combined_plot, legend, nrow=2, heights=c(8.5,2), top = "Sensitivity plots for Setting 1 (\U03B2 = 100)")
sens_plot_file <- "/Users/reetikasarkar/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_beta/beta100/sens.png"
combined_sens_plot
ggsave(filename = sens_plot_file, plot = combined_sens_plot)

## specificity plots
#confidence thresholds
mean_spec_conf <- as.numeric(c(conf_results_p_0_1_beta100[2,], conf_results_p_0_3_beta100[2,], conf_results_p_0_5_beta100[2,]))

#prr thresholds
mean_spec_prr <- as.numeric(c(prr_results_p_0_1_beta100[2,], prr_results_p_0_3_beta100[2,], prr_results_p_0_5_beta100[2,]))

#rr thresholds
mean_spec_rr <- as.numeric(c(rr_results_p_0_1_beta100[2,], rr_results_p_0_3_beta100[2,], rr_results_p_0_5_beta100[2,]))

#ror thresholds
mean_spec_ror <- as.numeric(c(ror_results_p_0_1_beta100[2,], ror_results_p_0_3_beta100[2,], ror_results_p_0_5_beta100[2,]))

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_spec_conf, group=p, color=p)) + 
  geom_point(aes(x=conf_thresh, y=mean_spec_conf, group=p, color=p)) + 
  ylim(0.5,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_spec_prr, group=p, color=p)) + 
  geom_point(aes(x=prr_thresh, y=mean_spec_prr, group=p, color=p)) +
  ylim(0.5,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_spec_rr, group=p, color=p)) + 
  geom_point(aes(x=rr_thresh, y=mean_spec_rr, group=p, color=p)) +
  ylim(0.5,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_spec_ror, group=p, color=p)) + 
  geom_point(aes(x=ror_thresh, y=mean_spec_ror, group=p, color=p)) +
  ylim(0.5,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2)

g1_legend <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_spec_conf, group=p, color=p)) + 
  geom_point(aes(x=conf_thresh, y=mean_spec_conf, color=p)) + 
  ylim(0.5,1) +
  #scale_shape_manual(values = c(15,16,17,18), name=greeks("beta")) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99"), name="p") +
  labs(y="Mean Specificity", x="Confidence thresholds") + 
  #scale_color_discrete(name=greeks("rho")) +
  #scale_shape_discrete(name=greeks("beta")) +
  #scale_linetype_discrete(name=greeks("beta")) +
  theme(legend.position = "bottom", axis.text=element_text(size=10), axis.title=element_text(size=8), legend.title = element_text(size=10, face="bold"), legend.text = element_text(size=8))

#function to extract legend from plot
get_only_legend <- function(plot) {
  plot_table <- ggplot_gtable(ggplot_build(plot))
  legend_plot <- which(sapply(plot_table$grobs, function(x) x$name) == "guide-box")
  legend <- plot_table$grobs[[legend_plot]]
  return(legend)
}

#extract legend from g1 using above function
legend <- get_only_legend(g1_legend)

combined_spec_plot <- grid.arrange(combined_plot, legend, nrow=2, heights=c(8.5,2), top = "Specificity plots for Setting 1 (\U03B2 = 100)")

spec_plot_file <- "/Users/reetikasarkar/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_beta/beta100/spec.png"
combined_spec_plot
ggsave(filename = spec_plot_file, plot = combined_spec_plot)

## overall accuracy plots
#confidence thresholds
mean_acc_conf <- as.numeric(c(conf_results_p_0_1_beta100[5,], conf_results_p_0_3_beta100[5,], conf_results_p_0_5_beta100[5,]))

#prr thresholds
mean_acc_prr <- as.numeric(c(prr_results_p_0_1_beta100[5,], prr_results_p_0_3_beta100[5,], prr_results_p_0_5_beta100[5,]))

#rr thresholds
mean_acc_rr <- as.numeric(c(rr_results_p_0_1_beta100[5,], rr_results_p_0_3_beta100[5,], rr_results_p_0_5_beta100[5,]))

#ror thresholds
mean_acc_ror <- as.numeric(c(ror_results_p_0_1_beta100[5,], ror_results_p_0_3_beta100[5,], ror_results_p_0_5_beta100[5,]))

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_acc_conf, group=p, color=p)) + 
  geom_point(aes(x=conf_thresh, y=mean_acc_conf, color=p)) + 
  ylim(0.6,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_acc_prr, group=p, color=p)) + 
  geom_point(aes(x=prr_thresh, y=mean_acc_prr, color=p)) +
  ylim(0.6,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_acc_rr, group=p, color=p)) + 
  geom_point(aes(x=rr_thresh, y=mean_acc_rr, color=p)) +
  ylim(0.6,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_acc_ror, group=p, color=p)) + 
  geom_point(aes(x=ror_thresh, y=mean_acc_ror, color=p)) +
  ylim(0.6,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2)

g1_legend <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_acc_conf, group=p, color=p)) + 
  geom_point(aes(x=conf_thresh, y=mean_acc_conf, color=p)) + 
  ylim(0.6,1) +
  #scale_shape_manual(values = c(15,16,17,18), name=greeks("beta")) +
  scale_color_manual(values = c("#1f78b4","#b2df8a","#fb9a99"), name="p") +
  labs(y="Mean Specificity", x="Confidence thresholds") + 
  #scale_color_discrete(name=greeks("rho")) +
  #scale_shape_discrete(name=greeks("beta")) +
  #scale_linetype_discrete(name=greeks("beta")) +
  theme(legend.position = "bottom", axis.text=element_text(size=10), axis.title=element_text(size=8), legend.title = element_text(size=10, face="bold"), legend.text = element_text(size=8))

#function to extract legend from plot
get_only_legend <- function(plot) {
  plot_table <- ggplot_gtable(ggplot_build(plot))
  legend_plot <- which(sapply(plot_table$grobs, function(x) x$name) == "guide-box")
  legend <- plot_table$grobs[[legend_plot]]
  return(legend)
}

#extract legend from g1 using above function
legend <- get_only_legend(g1_legend)

combined_acc_plot <- grid.arrange(combined_plot, legend, nrow=2, heights=c(8.5,2), top = "Overall Accuracy plots for Setting 1 (\U03B2 = 100)")

acc_plot_file <- "/Users/reetikasarkar/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_beta/beta100/acc.png"
combined_acc_plot
ggsave(filename = acc_plot_file, plot = combined_acc_plot)
```

## fixed p
```{r p_0_1}
conf_thresh <- as.factor(rep(c(0.4,0.5,0.6,0.7), 4))
prr_thresh <- as.factor(rep(c(1,1.2,1.5,2), 4))
rr_thresh <- as.factor(rep(c(1,1.2,1.5,2), 4))
ror_thresh <- as.factor(rep(c(1,1.2,1.5,2), 4))
betas <- as.factor(c(rep(1,4), rep(10, 4), rep(50, 4), rep(100, 4)))

#sensitivity plots
#confidence thresholds
mean_sens_conf <- as.numeric(c(conf_results_p_0_1_beta1[1,], conf_results_p_0_1_beta10[1,], conf_results_p_0_1_beta50[1,], conf_results_p_0_1_beta100[1,]))

#prr thresholds
mean_sens_prr <- as.numeric(c(prr_results_p_0_1_beta1[1,], prr_results_p_0_1_beta10[1,], prr_results_p_0_1_beta50[1,], prr_results_p_0_1_beta100[1,]))

#rr thresholds
mean_sens_rr <- as.numeric(c(rr_results_p_0_1_beta1[1,], rr_results_p_0_1_beta10[1,], rr_results_p_0_1_beta50[1,], rr_results_p_0_1_beta100[1,]))

#ror thresholds
mean_sens_ror <- as.numeric(c(ror_results_p_0_1_beta1[1,], ror_results_p_0_1_beta10[1,], ror_results_p_0_1_beta50[1,], ror_results_p_0_1_beta100[1,]))

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_sens_conf, group=betas, color = betas)) + 
  geom_point(aes(x=conf_thresh, y=mean_sens_conf, color = betas)) + 
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_sens_prr, group=betas, color = betas)) + 
  geom_point(aes(x=prr_thresh, y=mean_sens_prr, color = betas)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_sens_rr, group=betas, color = betas)) + 
  geom_point(aes(x=rr_thresh, y=mean_sens_rr, color = betas)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_sens_ror, group=betas, color = betas)) + 
  geom_point(aes(x=ror_thresh, y=mean_sens_ror, color = betas)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2)

g1_legend <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_sens_conf, group=betas, color=betas)) + 
  geom_point(aes(x=conf_thresh, y=mean_sens_conf, color=betas)) + 
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18), name=greeks("beta")) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#fb9a99"), name="\U03B2") +
  labs(y="Mean Sensitivity", x="Confidence thresholds") + 
  #scale_color_discrete(name=greeks("rho")) +
  #scale_shape_discrete(name=greeks("beta")) +
  #scale_linetype_discrete(name=greeks("beta")) +
  theme(legend.position = "bottom", axis.text=element_text(size=10),
        axis.title=element_text(size=8), legend.title = element_text(size=10, face="bold"), 
        legend.text = element_text(size=8))

#function to extract legend from plot
get_only_legend <- function(plot) {
  plot_table <- ggplot_gtable(ggplot_build(plot))
  legend_plot <- which(sapply(plot_table$grobs, function(x) x$name) == "guide-box")
  legend <- plot_table$grobs[[legend_plot]]
  return(legend)
}

#extract legend from g1 using above function
legend <- get_only_legend(g1_legend)

#final combined Sensitivity plot with common legend
combined_sens_plot <- grid.arrange(combined_plot, legend, nrow=2, heights=c(8.5,2), top = "Sensitivity plots for Setting 1 (p = 0.1)")
sens_plot_file <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_p/p_0_1/sens.png"
combined_sens_plot
ggsave(filename = sens_plot_file, plot = combined_sens_plot)

## specificity plots
#confidence thresholds
mean_spec_conf <- as.numeric(c(conf_results_p_0_1_beta1[2,], conf_results_p_0_1_beta10[2,], conf_results_p_0_1_beta50[2,], conf_results_p_0_1_beta100[2,]))

#prr thresholds
mean_spec_prr <- as.numeric(c(prr_results_p_0_1_beta1[2,], prr_results_p_0_1_beta10[2,], prr_results_p_0_1_beta50[2,], prr_results_p_0_1_beta100[2,]))

#rr thresholds
mean_spec_rr <- as.numeric(c(rr_results_p_0_1_beta1[2,], rr_results_p_0_1_beta10[2,], rr_results_p_0_1_beta50[2,], rr_results_p_0_1_beta100[2,]))

#ror thresholds
mean_spec_ror <- as.numeric(c(ror_results_p_0_1_beta1[2,], ror_results_p_0_1_beta10[2,], ror_results_p_0_1_beta50[2,], ror_results_p_0_1_beta100[2,]))

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_spec_conf, group=betas, color=betas)) + 
  geom_point(aes(x=conf_thresh, y=mean_spec_conf, color=betas)) + 
  ylim(0.75,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_spec_prr, group=betas, color=betas)) + 
  geom_point(aes(x=prr_thresh, y=mean_spec_prr, color=betas)) +
  ylim(0.75,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_spec_rr, group=betas, color=betas)) + 
  geom_point(aes(x=rr_thresh, y=mean_spec_rr, color=betas)) +
  ylim(0.75,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_spec_ror, group=betas, color=betas)) + 
  geom_point(aes(x=ror_thresh, y=mean_spec_ror, color=betas)) +
  ylim(0.75,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2)

g1_legend <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_spec_conf, group=betas, color=betas)) + 
  geom_point(aes(x=conf_thresh, y=mean_spec_conf, color=betas)) + 
  ylim(0.75,1) +
  #scale_shape_manual(values = c(15,16,17,18), name=greeks("beta")) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#fb9a99"), name="\U03B2") +
  labs(y="Mean Specificity", x="Confidence thresholds") + 
  #scale_color_discrete(name=greeks("rho")) +
  #scale_shape_discrete(name=greeks("beta")) +
  #scale_linetype_discrete(name=greeks("beta")) +
  theme(legend.position = "bottom", axis.text=element_text(size=10), axis.title=element_text(size=8), legend.title = element_text(size=10, face="bold"), legend.text = element_text(size=8))

#function to extract legend from plot
get_only_legend <- function(plot) {
  plot_table <- ggplot_gtable(ggplot_build(plot))
  legend_plot <- which(sapply(plot_table$grobs, function(x) x$name) == "guide-box")
  legend <- plot_table$grobs[[legend_plot]]
  return(legend)
}

#extract legend from g1 using above function
legend <- get_only_legend(g1_legend)

combined_spec_plot <- grid.arrange(combined_plot, legend, nrow=2, heights=c(8.5,2), top = "Specificity plots for Setting 1 (p = 0.1)")

spec_plot_file <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_p/p_0_1/spec.png"
combined_spec_plot
ggsave(filename = spec_plot_file, plot = combined_spec_plot)

## overall accuracy plots
#confidence thresholds
mean_acc_conf <- as.numeric(c(conf_results_p_0_1_beta1[5,], conf_results_p_0_1_beta10[5,], conf_results_p_0_1_beta50[5,], conf_results_p_0_1_beta100[5,]))

#prr thresholds
mean_acc_prr <- as.numeric(c(prr_results_p_0_1_beta1[5,], prr_results_p_0_1_beta10[5,], prr_results_p_0_1_beta50[5,], prr_results_p_0_1_beta100[5,]))

#rr thresholds
mean_acc_rr <- as.numeric(c(rr_results_p_0_1_beta1[5,], rr_results_p_0_1_beta10[5,], rr_results_p_0_1_beta50[5,], rr_results_p_0_1_beta100[5,]))

#ror thresholds
mean_acc_ror <- as.numeric(c(ror_results_p_0_1_beta1[5,], ror_results_p_0_1_beta10[5,], ror_results_p_0_1_beta50[5,], ror_results_p_0_1_beta100[5,]))

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_acc_conf, group=betas, color=betas)) + 
  geom_point(aes(x=conf_thresh, y=mean_acc_conf, color=betas)) + 
  ylim(0.8,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_acc_prr, group=betas, color=betas)) + 
  geom_point(aes(x=prr_thresh, y=mean_acc_prr, color=betas)) +
  ylim(0.8,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_acc_rr, group=betas, color=betas)) + 
  geom_point(aes(x=rr_thresh, y=mean_acc_rr, color=betas)) +
  ylim(0.8,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_acc_ror, group=betas, color=betas)) + 
  geom_point(aes(x=ror_thresh, y=mean_acc_ror, color=betas)) +
  ylim(0.8,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2)

g1_legend <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_spec_conf, group=betas, color=betas)) + 
  geom_point(aes(x=conf_thresh, y=mean_spec_conf, color=betas)) + 
  ylim(0.8,1) +
  #scale_shape_manual(values = c(15,16,17,18), name=greeks("beta")) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#fb9a99"), name="\U03B2") +
  labs(y="Mean Specificity", x="Confidence thresholds") + 
  #scale_color_discrete(name=greeks("rho")) +
  #scale_shape_discrete(name=greeks("beta")) +
  #scale_linetype_discrete(name=greeks("beta")) +
  theme(legend.position = "bottom", axis.text=element_text(size=10), axis.title=element_text(size=8), legend.title = element_text(size=10, face="bold"), legend.text = element_text(size=8))

#function to extract legend from plot
get_only_legend <- function(plot) {
  plot_table <- ggplot_gtable(ggplot_build(plot))
  legend_plot <- which(sapply(plot_table$grobs, function(x) x$name) == "guide-box")
  legend <- plot_table$grobs[[legend_plot]]
  return(legend)
}

#extract legend from g1 using above function
legend <- get_only_legend(g1_legend)

combined_acc_plot <- grid.arrange(combined_plot, legend, nrow=2, heights=c(8.5,2), top = "Overall Accuracy plots for Setting 1 (p = 0.1)")

acc_plot_file <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_p/p_0_1/acc.png"
combined_acc_plot
ggsave(filename = acc_plot_file, plot = combined_acc_plot)
```

```{r p_0_3}
conf_thresh <- as.factor(rep(c(0.4,0.5,0.6,0.7), 4))
prr_thresh <- as.factor(rep(c(1,1.2,1.5,2), 4))
rr_thresh <- as.factor(rep(c(1,1.2,1.5,2), 4))
ror_thresh <- as.factor(rep(c(1,1.2,1.5,2), 4))
betas <- as.factor(c(rep(1,4), rep(10, 4), rep(50, 4), rep(100, 4)))

#sensitivity plots
#confidence thresholds
mean_sens_conf <- as.numeric(c(conf_results_p_0_3_beta1[1,], conf_results_p_0_3_beta10[1,], conf_results_p_0_3_beta50[1,], conf_results_p_0_3_beta100[1,]))

#prr thresholds
mean_sens_prr <- as.numeric(c(prr_results_p_0_3_beta1[1,], prr_results_p_0_3_beta10[1,], prr_results_p_0_3_beta50[1,], prr_results_p_0_3_beta100[1,]))

#rr thresholds
mean_sens_rr <- as.numeric(c(rr_results_p_0_3_beta1[1,], rr_results_p_0_3_beta10[1,], rr_results_p_0_3_beta50[1,], rr_results_p_0_3_beta100[1,]))

#ror thresholds
mean_sens_ror <- as.numeric(c(ror_results_p_0_3_beta1[1,], ror_results_p_0_3_beta10[1,], ror_results_p_0_3_beta50[1,], ror_results_p_0_3_beta100[1,]))

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_sens_conf, group=betas, color = betas)) + 
  geom_point(aes(x=conf_thresh, y=mean_sens_conf, color = betas)) + 
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_sens_prr, group=betas, color = betas)) + 
  geom_point(aes(x=prr_thresh, y=mean_sens_prr, color = betas)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_sens_rr, group=betas, color = betas)) + 
  geom_point(aes(x=rr_thresh, y=mean_sens_rr, color = betas)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_sens_ror, group=betas, color = betas)) + 
  geom_point(aes(x=ror_thresh, y=mean_sens_ror, color = betas)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2)

g1_legend <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_sens_conf, group=betas, color=betas)) + 
  geom_point(aes(x=conf_thresh, y=mean_sens_conf, color=betas)) + 
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18), name=greeks("beta")) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#fb9a99"), name="\U03B2") +
  labs(y="Mean Sensitivity", x="Confidence thresholds") + 
  #scale_color_discrete(name=greeks("rho")) +
  #scale_shape_discrete(name=greeks("beta")) +
  #scale_linetype_discrete(name=greeks("beta")) +
  theme(legend.position = "bottom", axis.text=element_text(size=10),
        axis.title=element_text(size=8), legend.title = element_text(size=10, face="bold"), 
        legend.text = element_text(size=8))

#function to extract legend from plot
get_only_legend <- function(plot) {
  plot_table <- ggplot_gtable(ggplot_build(plot))
  legend_plot <- which(sapply(plot_table$grobs, function(x) x$name) == "guide-box")
  legend <- plot_table$grobs[[legend_plot]]
  return(legend)
}

#extract legend from g1 using above function
legend <- get_only_legend(g1_legend)

#final combined Sensitivity plot with common legend
combined_sens_plot <- grid.arrange(combined_plot, legend, nrow=2, heights=c(8.5,2), top = "Sensitivity plots for Setting 1 (p = 0.3)")
sens_plot_file <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_p/p_0_3/sens.png"
combined_sens_plot
ggsave(filename = sens_plot_file, plot = combined_sens_plot)

## specificity plots
#confidence thresholds
mean_spec_conf <- as.numeric(c(conf_results_p_0_3_beta1[2,], conf_results_p_0_3_beta10[2,], conf_results_p_0_3_beta50[2,], conf_results_p_0_3_beta100[2,]))

#prr thresholds
mean_spec_prr <- as.numeric(c(prr_results_p_0_3_beta1[2,], prr_results_p_0_3_beta10[2,], prr_results_p_0_3_beta50[2,], prr_results_p_0_3_beta100[2,]))

#rr thresholds
mean_spec_rr <- as.numeric(c(rr_results_p_0_3_beta1[2,], rr_results_p_0_3_beta10[2,], rr_results_p_0_3_beta50[2,], rr_results_p_0_3_beta100[2,]))

#ror thresholds
mean_spec_ror <- as.numeric(c(ror_results_p_0_3_beta1[2,], ror_results_p_0_3_beta10[2,], ror_results_p_0_3_beta50[2,], ror_results_p_0_3_beta100[2,]))

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_spec_conf, group=betas, color=betas)) + 
  geom_point(aes(x=conf_thresh, y=mean_spec_conf, color=betas)) + 
  ylim(0.75,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_spec_prr, group=betas, color=betas)) + 
  geom_point(aes(x=prr_thresh, y=mean_spec_prr, color=betas)) +
  ylim(0.75,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_spec_rr, group=betas, color=betas)) + 
  geom_point(aes(x=rr_thresh, y=mean_spec_rr, color=betas)) +
  ylim(0.75,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_spec_ror, group=betas, color=betas)) + 
  geom_point(aes(x=ror_thresh, y=mean_spec_ror, color=betas)) +
  ylim(0.75,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2)

g1_legend <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_spec_conf, group=betas, color=betas)) + 
  geom_point(aes(x=conf_thresh, y=mean_spec_conf, color=betas)) + 
  ylim(0.75,1) +
  #scale_shape_manual(values = c(15,16,17,18), name=greeks("beta")) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#fb9a99"), name="\U03B2") +
  labs(y="Mean Specificity", x="Confidence thresholds") + 
  #scale_color_discrete(name=greeks("rho")) +
  #scale_shape_discrete(name=greeks("beta")) +
  #scale_linetype_discrete(name=greeks("beta")) +
  theme(legend.position = "bottom", axis.text=element_text(size=10), axis.title=element_text(size=8), legend.title = element_text(size=10, face="bold"), legend.text = element_text(size=8))

#function to extract legend from plot
get_only_legend <- function(plot) {
  plot_table <- ggplot_gtable(ggplot_build(plot))
  legend_plot <- which(sapply(plot_table$grobs, function(x) x$name) == "guide-box")
  legend <- plot_table$grobs[[legend_plot]]
  return(legend)
}

#extract legend from g1 using above function
legend <- get_only_legend(g1_legend)

combined_spec_plot <- grid.arrange(combined_plot, legend, nrow=2, heights=c(8.5,2), top = "Specificity plots for Setting 1 (p = 0.3)")

spec_plot_file <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_p/p_0_3/spec.png"
combined_spec_plot
ggsave(filename = spec_plot_file, plot = combined_spec_plot)

## overall accuracy plots
#confidence thresholds
mean_acc_conf <- as.numeric(c(conf_results_p_0_3_beta1[5,], conf_results_p_0_3_beta10[5,], conf_results_p_0_3_beta50[5,], conf_results_p_0_3_beta100[5,]))

#prr thresholds
mean_acc_prr <- as.numeric(c(prr_results_p_0_3_beta1[5,], prr_results_p_0_3_beta10[5,], prr_results_p_0_3_beta50[5,], prr_results_p_0_3_beta100[5,]))

#rr thresholds
mean_acc_rr <- as.numeric(c(rr_results_p_0_3_beta1[5,], rr_results_p_0_3_beta10[5,], rr_results_p_0_3_beta50[5,], rr_results_p_0_3_beta100[5,]))

#ror thresholds
mean_acc_ror <- as.numeric(c(ror_results_p_0_3_beta1[5,], ror_results_p_0_3_beta10[5,], ror_results_p_0_3_beta50[5,], ror_results_p_0_3_beta100[5,]))

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_acc_conf, group=betas, color=betas)) + 
  geom_point(aes(x=conf_thresh, y=mean_acc_conf, color=betas)) + 
  ylim(0.8,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_acc_prr, group=betas, color=betas)) + 
  geom_point(aes(x=prr_thresh, y=mean_acc_prr, color=betas)) +
  ylim(0.8,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_acc_rr, group=betas, color=betas)) + 
  geom_point(aes(x=rr_thresh, y=mean_acc_rr, color=betas)) +
  ylim(0.8,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_acc_ror, group=betas, color=betas)) + 
  geom_point(aes(x=ror_thresh, y=mean_acc_ror, color=betas)) +
  ylim(0.8,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2)

g1_legend <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_spec_conf, group=betas, color=betas)) + 
  geom_point(aes(x=conf_thresh, y=mean_spec_conf, color=betas)) + 
  ylim(0.8,1) +
  #scale_shape_manual(values = c(15,16,17,18), name=greeks("beta")) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#fb9a99"), name="\U03B2") +
  labs(y="Mean Specificity", x="Confidence thresholds") + 
  #scale_color_discrete(name=greeks("rho")) +
  #scale_shape_discrete(name=greeks("beta")) +
  #scale_linetype_discrete(name=greeks("beta")) +
  theme(legend.position = "bottom", axis.text=element_text(size=10), axis.title=element_text(size=8), legend.title = element_text(size=10, face="bold"), legend.text = element_text(size=8))

#function to extract legend from plot
get_only_legend <- function(plot) {
  plot_table <- ggplot_gtable(ggplot_build(plot))
  legend_plot <- which(sapply(plot_table$grobs, function(x) x$name) == "guide-box")
  legend <- plot_table$grobs[[legend_plot]]
  return(legend)
}

#extract legend from g1 using above function
legend <- get_only_legend(g1_legend)

combined_acc_plot <- grid.arrange(combined_plot, legend, nrow=2, heights=c(8.5,2), top = "Overall Accuracy plots for Setting 1 (p = 0.3)")

acc_plot_file <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_p/p_0_3/acc.png"
combined_acc_plot
ggsave(filename = acc_plot_file, plot = combined_acc_plot)
```

```{r p_0_5}
conf_thresh <- as.factor(rep(c(0.4,0.5,0.6,0.7), 4))
prr_thresh <- as.factor(rep(c(1,1.2,1.5,2), 4))
rr_thresh <- as.factor(rep(c(1,1.2,1.5,2), 4))
ror_thresh <- as.factor(rep(c(1,1.2,1.5,2), 4))
betas <- as.factor(c(rep(1,4), rep(10, 4), rep(50, 4), rep(100, 4)))

#sensitivity plots
#confidence thresholds
mean_sens_conf <- as.numeric(c(conf_results_p_0_5_beta1[1,], conf_results_p_0_5_beta10[1,], conf_results_p_0_5_beta50[1,], conf_results_p_0_5_beta100[1,]))

#prr thresholds
mean_sens_prr <- as.numeric(c(prr_results_p_0_5_beta1[1,], prr_results_p_0_5_beta10[1,], prr_results_p_0_5_beta50[1,], prr_results_p_0_5_beta100[1,]))

#rr thresholds
mean_sens_rr <- as.numeric(c(rr_results_p_0_5_beta1[1,], rr_results_p_0_5_beta10[1,], rr_results_p_0_5_beta50[1,], rr_results_p_0_5_beta100[1,]))

#ror thresholds
mean_sens_ror <- as.numeric(c(ror_results_p_0_5_beta1[1,], ror_results_p_0_5_beta10[1,], ror_results_p_0_5_beta50[1,], ror_results_p_0_5_beta100[1,]))

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_sens_conf, group=betas, color = betas)) + 
  geom_point(aes(x=conf_thresh, y=mean_sens_conf, color = betas)) + 
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_sens_prr, group=betas, color = betas)) + 
  geom_point(aes(x=prr_thresh, y=mean_sens_prr, color = betas)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_sens_rr, group=betas, color = betas)) + 
  geom_point(aes(x=rr_thresh, y=mean_sens_rr, color = betas)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_sens_ror, group=betas, color = betas)) + 
  geom_point(aes(x=ror_thresh, y=mean_sens_ror, color = betas)) +
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Sensitivity", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2)

g1_legend <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_sens_conf, group=betas, color=betas)) + 
  geom_point(aes(x=conf_thresh, y=mean_sens_conf, color=betas)) + 
  ylim(0,1) +
  #scale_shape_manual(values = c(15,16,17,18), name=greeks("beta")) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#fb9a99"), name="\U03B2") +
  labs(y="Mean Sensitivity", x="Confidence thresholds") + 
  #scale_color_discrete(name=greeks("rho")) +
  #scale_shape_discrete(name=greeks("beta")) +
  #scale_linetype_discrete(name=greeks("beta")) +
  theme(legend.position = "bottom", axis.text=element_text(size=10),
        axis.title=element_text(size=8), legend.title = element_text(size=10, face="bold"), 
        legend.text = element_text(size=8))

#function to extract legend from plot
get_only_legend <- function(plot) {
  plot_table <- ggplot_gtable(ggplot_build(plot))
  legend_plot <- which(sapply(plot_table$grobs, function(x) x$name) == "guide-box")
  legend <- plot_table$grobs[[legend_plot]]
  return(legend)
}

#extract legend from g1 using above function
legend <- get_only_legend(g1_legend)

#final combined Sensitivity plot with common legend
combined_sens_plot <- grid.arrange(combined_plot, legend, nrow=2, heights=c(8.5,2), top = "Sensitivity plots for Setting 1 (p = 0.5)")
sens_plot_file <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_p/p_0_5/sens.png"
combined_sens_plot
ggsave(filename = sens_plot_file, plot = combined_sens_plot)

## specificity plots
#confidence thresholds
mean_spec_conf <- as.numeric(c(conf_results_p_0_1_beta1[2,], conf_results_p_0_1_beta10[2,], conf_results_p_0_1_beta50[2,], conf_results_p_0_1_beta100[2,]))

#prr thresholds
mean_spec_prr <- as.numeric(c(prr_results_p_0_1_beta1[2,], prr_results_p_0_1_beta10[2,], prr_results_p_0_1_beta50[2,], prr_results_p_0_1_beta100[2,]))

#rr thresholds
mean_spec_rr <- as.numeric(c(rr_results_p_0_1_beta1[2,], rr_results_p_0_1_beta10[2,], rr_results_p_0_1_beta50[2,], rr_results_p_0_1_beta100[2,]))

#ror thresholds
mean_spec_ror <- as.numeric(c(ror_results_p_0_1_beta1[2,], ror_results_p_0_1_beta10[2,], ror_results_p_0_1_beta50[2,], ror_results_p_0_1_beta100[2,]))

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_spec_conf, group=betas, color=betas)) + 
  geom_point(aes(x=conf_thresh, y=mean_spec_conf, color=betas)) + 
  ylim(0.75,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_spec_prr, group=betas, color=betas)) + 
  geom_point(aes(x=prr_thresh, y=mean_spec_prr, color=betas)) +
  ylim(0.75,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_spec_rr, group=betas, color=betas)) + 
  geom_point(aes(x=rr_thresh, y=mean_spec_rr, color=betas)) +
  ylim(0.75,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_spec_ror, group=betas, color=betas)) + 
  geom_point(aes(x=ror_thresh, y=mean_spec_ror, color=betas)) +
  ylim(0.75,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Specificity", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2)

g1_legend <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_spec_conf, group=betas, color=betas)) + 
  geom_point(aes(x=conf_thresh, y=mean_spec_conf, color=betas)) + 
  ylim(0.75,1) +
  #scale_shape_manual(values = c(15,16,17,18), name=greeks("beta")) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#fb9a99"), name="\U03B2") +
  labs(y="Mean Specificity", x="Confidence thresholds") + 
  #scale_color_discrete(name=greeks("rho")) +
  #scale_shape_discrete(name=greeks("beta")) +
  #scale_linetype_discrete(name=greeks("beta")) +
  theme(legend.position = "bottom", axis.text=element_text(size=10), axis.title=element_text(size=8), legend.title = element_text(size=10, face="bold"), legend.text = element_text(size=8))

#function to extract legend from plot
get_only_legend <- function(plot) {
  plot_table <- ggplot_gtable(ggplot_build(plot))
  legend_plot <- which(sapply(plot_table$grobs, function(x) x$name) == "guide-box")
  legend <- plot_table$grobs[[legend_plot]]
  return(legend)
}

#extract legend from g1 using above function
legend <- get_only_legend(g1_legend)

combined_spec_plot <- grid.arrange(combined_plot, legend, nrow=2, heights=c(8.5,2), top = "Specificity plots for Setting 1 (p = 0.5)")

spec_plot_file <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_p/p_0_5/spec.png"
combined_spec_plot
ggsave(filename = spec_plot_file, plot = combined_spec_plot)

## overall accuracy plots
#confidence thresholds
mean_acc_conf <- as.numeric(c(conf_results_p_0_5_beta1[5,], conf_results_p_0_5_beta10[5,], conf_results_p_0_5_beta50[5,], conf_results_p_0_5_beta100[5,]))

#prr thresholds
mean_acc_prr <- as.numeric(c(prr_results_p_0_5_beta1[5,], prr_results_p_0_5_beta10[5,], prr_results_p_0_5_beta50[5,], prr_results_p_0_5_beta100[5,]))

#rr thresholds
mean_acc_rr <- as.numeric(c(rr_results_p_0_5_beta1[5,], rr_results_p_0_5_beta10[5,], rr_results_p_0_5_beta50[5,], rr_results_p_0_5_beta100[5,]))

#ror thresholds
mean_acc_ror <- as.numeric(c(ror_results_p_0_5_beta1[5,], ror_results_p_0_5_beta10[5,], ror_results_p_0_5_beta50[5,], ror_results_p_0_5_beta100[5,]))

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_acc_conf, group=betas, color=betas)) + 
  geom_point(aes(x=conf_thresh, y=mean_acc_conf, color=betas)) + 
  ylim(0.6,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_acc_prr, group=betas, color=betas)) + 
  geom_point(aes(x=prr_thresh, y=mean_acc_prr, color=betas)) +
  ylim(0.6,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_acc_rr, group=betas, color=betas)) + 
  geom_point(aes(x=rr_thresh, y=mean_acc_rr, color=betas)) +
  ylim(0.6,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_acc_ror, group=betas, color=betas)) + 
  geom_point(aes(x=ror_thresh, y=mean_acc_ror, color=betas)) +
  ylim(0.6,1) +
  #scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#fb9a99")) +
  labs(y="Mean Overall Accuracy", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2)

g1_legend <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_spec_conf, group=betas, color=betas)) + 
  geom_point(aes(x=conf_thresh, y=mean_spec_conf, color=betas)) + 
  ylim(0.6,1) +
  #scale_shape_manual(values = c(15,16,17,18), name=greeks("beta")) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#fb9a99"), name="\U03B2") +
  labs(y="Mean Specificity", x="Confidence thresholds") + 
  #scale_color_discrete(name=greeks("rho")) +
  #scale_shape_discrete(name=greeks("beta")) +
  #scale_linetype_discrete(name=greeks("beta")) +
  theme(legend.position = "bottom", axis.text=element_text(size=10), axis.title=element_text(size=8), legend.title = element_text(size=10, face="bold"), legend.text = element_text(size=8))

#function to extract legend from plot
get_only_legend <- function(plot) {
  plot_table <- ggplot_gtable(ggplot_build(plot))
  legend_plot <- which(sapply(plot_table$grobs, function(x) x$name) == "guide-box")
  legend <- plot_table$grobs[[legend_plot]]
  return(legend)
}

#extract legend from g1 using above function
legend <- get_only_legend(g1_legend)

combined_acc_plot <- grid.arrange(combined_plot, legend, nrow=2, heights=c(8.5,2), top = "Overall Accuracy plots for Setting 1 (p = 0.5)")

acc_plot_file <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/plots/setting_1d_3ae/fixed_p/p_0_5/acc.png"
combined_acc_plot
ggsave(filename = acc_plot_file, plot = combined_acc_plot)
```
