---
title: "Plots for accuracy measures"
author: "Reetika Sarkar"
output: html_document
---

```{r load_libraries}
## SETTING 2: p=0.1
#plots for accuracy measures

library(ggplot2)
library(gridExtra)
library(ggpubr)
library(greekLetters)
```

```{r read_results_data}
#read file from drive
results_loc_beta1 <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/codes/results/naive_setting_3d_5ae/p_0_1/beta_1"
results_loc_beta10 <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/codes/results/naive_setting_3d_5ae/p_0_1/beta_10"
results_loc_beta50 <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/codes/results/naive_setting_3d_5ae/p_0_1/beta_50"
results_loc_beta100 <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/codes/results/naive_setting_3d_5ae/p_0_1/beta_100"

results_loc_beta1_dep_0_3 <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/codes/results/correlated_setting_3d_5ae/p_0_1/cor_0_3/beta_1/model_1"
results_loc_beta10_dep_0_3 <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/codes/results/correlated_setting_3d_5ae/p_0_1/cor_0_3/beta_10/model_1"
results_loc_beta50_dep_0_3 <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/codes/results/correlated_setting_3d_5ae/p_0_1/cor_0_3/beta_50/model_1"
results_loc_beta100_dep_0_3 <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/codes/results/correlated_setting_3d_5ae/p_0_1/cor_0_3/beta_100/model_1"

results_loc_beta1_dep_0_5 <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/codes/results/correlated_setting_3d_5ae/p_0_1/cor_0_5/beta_1/model_1"
results_loc_beta10_dep_0_5 <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/codes/results/correlated_setting_3d_5ae/p_0_1/cor_0_5/beta_10/model_1"
results_loc_beta50_dep_0_5 <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/codes/results/correlated_setting_3d_5ae/p_0_1/cor_0_5/beta_50/model_1"
results_loc_beta100_dep_0_5 <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/codes/results/correlated_setting_3d_5ae/p_0_1/cor_0_5/beta_100/model_1"

results_loc_beta1_dep_0_7 <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/codes/results/correlated_setting_3d_5ae/p_0_1/cor_0_7/beta_1/model_1"
results_loc_beta10_dep_0_7 <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/codes/results/correlated_setting_3d_5ae/p_0_1/cor_0_7/beta_10/model_1"
results_loc_beta50_dep_0_7 <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/codes/results/correlated_setting_3d_5ae/p_0_1/cor_0_7/beta_50/model_1"
results_loc_beta100_dep_0_7 <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/codes/results/correlated_setting_3d_5ae/p_0_1/cor_0_7/beta_100/model_1"

#read conf values for each beta 
# independent setting
conf_results_beta1 <- read.table(paste0(results_loc_beta1,"/conf.csv"), header = T)
conf_results_beta10 <- read.table(paste0(results_loc_beta10,"/conf.csv"), header = T)
conf_results_beta50 <- read.table(paste0(results_loc_beta50,"/conf.csv"), header = T)
conf_results_beta100 <- read.table(paste0(results_loc_beta100,"/conf.csv"), header = T)

# dependent, cor = 0.3
conf_results_beta1_dep_0_3 <- read.table(paste0(results_loc_beta1_dep_0_3,"/conf.csv"), header = T)
conf_results_beta10_dep_0_3 <- read.table(paste0(results_loc_beta10_dep_0_3,"/conf.csv"), header = T)
conf_results_beta50_dep_0_3 <- read.table(paste0(results_loc_beta50_dep_0_3,"/conf.csv"), header = T)
conf_results_beta100_dep_0_3 <- read.table(paste0(results_loc_beta100_dep_0_3,"/conf.csv"), header = T)

# dependent, cor = 0.5
conf_results_beta1_dep_0_5 <- read.table(paste0(results_loc_beta1_dep_0_5,"/conf.csv"), header = T)
conf_results_beta10_dep_0_5 <- read.table(paste0(results_loc_beta10_dep_0_5,"/conf.csv"), header = T)
conf_results_beta50_dep_0_5 <- read.table(paste0(results_loc_beta50_dep_0_5,"/conf.csv"), header = T)
conf_results_beta100_dep_0_5 <- read.table(paste0(results_loc_beta100_dep_0_5,"/conf.csv"), header = T)

# dependent, cor = 0.7
conf_results_beta1_dep_0_7 <- read.table(paste0(results_loc_beta1_dep_0_7,"/conf.csv"), header = T)
conf_results_beta10_dep_0_7 <- read.table(paste0(results_loc_beta10_dep_0_7,"/conf.csv"), header = T)
conf_results_beta50_dep_0_7 <- read.table(paste0(results_loc_beta50_dep_0_7,"/conf.csv"), header = T)
conf_results_beta100_dep_0_7 <- read.table(paste0(results_loc_beta100_dep_0_7,"/conf.csv"), header = T)

###### read prr values for each beta
prr_results_beta1 <- read.table(paste0(results_loc_beta1,"/prr.csv"), header = T)
prr_results_beta10 <- read.table(paste0(results_loc_beta10,"/prr.csv"), header = T)
prr_results_beta50 <- read.table(paste0(results_loc_beta50,"/prr.csv"), header = T)
prr_results_beta100 <- read.table(paste0(results_loc_beta100,"/prr.csv"), header = T)

# dependent, cor = 0.3
prr_results_beta1_dep_0_3 <- read.table(paste0(results_loc_beta1_dep_0_3,"/prr.csv"), header = T)
prr_results_beta10_dep_0_3 <- read.table(paste0(results_loc_beta10_dep_0_3,"/prr.csv"), header = T)
prr_results_beta50_dep_0_3 <- read.table(paste0(results_loc_beta50_dep_0_3,"/prr.csv"), header = T)
prr_results_beta100_dep_0_3 <- read.table(paste0(results_loc_beta100_dep_0_3,"/prr.csv"), header = T)

# dependent, cor = 0.5
prr_results_beta1_dep_0_5 <- read.table(paste0(results_loc_beta1_dep_0_5,"/prr.csv"), header = T)
prr_results_beta10_dep_0_5 <- read.table(paste0(results_loc_beta10_dep_0_5,"/prr.csv"), header = T)
prr_results_beta50_dep_0_5 <- read.table(paste0(results_loc_beta50_dep_0_5,"/prr.csv"), header = T)
prr_results_beta100_dep_0_5 <- read.table(paste0(results_loc_beta100_dep_0_5,"/prr.csv"), header = T)

# dependent, cor = 0.7
prr_results_beta1_dep_0_7 <- read.table(paste0(results_loc_beta1_dep_0_7,"/prr.csv"), header = T)
prr_results_beta10_dep_0_7 <- read.table(paste0(results_loc_beta10_dep_0_7,"/prr.csv"), header = T)
prr_results_beta50_dep_0_7 <- read.table(paste0(results_loc_beta50_dep_0_7,"/prr.csv"), header = T)
prr_results_beta100_dep_0_7 <- read.table(paste0(results_loc_beta100_dep_0_7,"/prr.csv"), header = T)

##### read rr values for each beta
rr_results_beta1 <- read.table(paste0(results_loc_beta1,"/rr.csv"), header = T)
rr_results_beta10 <- read.table(paste0(results_loc_beta10,"/rr.csv"), header = T)
rr_results_beta50 <- read.table(paste0(results_loc_beta50,"/rr.csv"), header = T)
rr_results_beta100 <- read.table(paste0(results_loc_beta100,"/rr.csv"), header = T)

# dependent, cor = 0.3
rr_results_beta1_dep_0_3 <- read.table(paste0(results_loc_beta1_dep_0_3,"/rr.csv"), header = T)
rr_results_beta10_dep_0_3 <- read.table(paste0(results_loc_beta10_dep_0_3,"/rr.csv"), header = T)
rr_results_beta50_dep_0_3 <- read.table(paste0(results_loc_beta50_dep_0_3,"/rr.csv"), header = T)
rr_results_beta100_dep_0_3 <- read.table(paste0(results_loc_beta100_dep_0_3,"/rr.csv"), header = T)

# dependent, cor = 0.5
rr_results_beta1_dep_0_5 <- read.table(paste0(results_loc_beta1_dep_0_5,"/rr.csv"), header = T)
rr_results_beta10_dep_0_5 <- read.table(paste0(results_loc_beta10_dep_0_5,"/rr.csv"), header = T)
rr_results_beta50_dep_0_5 <- read.table(paste0(results_loc_beta50_dep_0_5,"/rr.csv"), header = T)
rr_results_beta100_dep_0_5 <- read.table(paste0(results_loc_beta100_dep_0_5,"/rr.csv"), header = T)

# dependent, cor = 0.7
rr_results_beta1_dep_0_7 <- read.table(paste0(results_loc_beta1_dep_0_7,"/rr.csv"), header = T)
rr_results_beta10_dep_0_7 <- read.table(paste0(results_loc_beta10_dep_0_7,"/rr.csv"), header = T)
rr_results_beta50_dep_0_7 <- read.table(paste0(results_loc_beta50_dep_0_7,"/rr.csv"), header = T)
rr_results_beta100_dep_0_7 <- read.table(paste0(results_loc_beta100_dep_0_7,"/rr.csv"), header = T)

#### read ror values for each beta
ror_results_beta1 <- read.table(paste0(results_loc_beta1,"/ror.csv"), header = T)
ror_results_beta10 <- read.table(paste0(results_loc_beta10,"/ror.csv"), header = T)
ror_results_beta50 <- read.table(paste0(results_loc_beta50,"/ror.csv"), header = T)
ror_results_beta100 <- read.table(paste0(results_loc_beta100,"/ror.csv"), header = T)

# dependent, cor = 0.3
ror_results_beta1_dep_0_3 <- read.table(paste0(results_loc_beta1_dep_0_3,"/ror.csv"), header = T)
ror_results_beta10_dep_0_3 <- read.table(paste0(results_loc_beta10_dep_0_3,"/ror.csv"), header = T)
ror_results_beta50_dep_0_3 <- read.table(paste0(results_loc_beta50_dep_0_3,"/ror.csv"), header = T)
ror_results_beta100_dep_0_3 <- read.table(paste0(results_loc_beta100_dep_0_3,"/ror.csv"), header = T)

# dependent, cor = 0.5
ror_results_beta1_dep_0_5 <- read.table(paste0(results_loc_beta1_dep_0_5,"/ror.csv"), header = T)
ror_results_beta10_dep_0_5 <- read.table(paste0(results_loc_beta10_dep_0_5,"/ror.csv"), header = T)
ror_results_beta50_dep_0_5 <- read.table(paste0(results_loc_beta50_dep_0_5,"/ror.csv"), header = T)
ror_results_beta100_dep_0_5 <- read.table(paste0(results_loc_beta100_dep_0_5,"/ror.csv"), header = T)

# dependent, cor = 0.7
ror_results_beta1_dep_0_7 <- read.table(paste0(results_loc_beta1_dep_0_7,"/ror.csv"), header = T)
ror_results_beta10_dep_0_7 <- read.table(paste0(results_loc_beta10_dep_0_7,"/ror.csv"), header = T)
ror_results_beta50_dep_0_7 <- read.table(paste0(results_loc_beta50_dep_0_7,"/ror.csv"), header = T)
ror_results_beta100_dep_0_7 <- read.table(paste0(results_loc_beta100_dep_0_7,"/ror.csv"), header = T)
```

```{r define_thresholds}
#greeks("beta") <- as.factor(rep(c(rep(1,4), rep(10,4), rep(50,4), rep(100,4)), 4)
betas <- as.factor(rep(c(rep(1,4), rep(10,4), rep(50,4), rep(100,4)), 4))
#greeks("rho") <- as.factor(c(rep(0, 16), rep(0.3, 16), rep(0.5, 16), rep(0.7, 16)))
corr <- as.factor(c(rep(0, 16), rep(0.3, 16), rep(0.5, 16), rep(0.7, 16)))
conf_thresh <- as.factor(rep(c(0.4,0.5,0.6,0.7),16))
prr_thresh <- as.factor(rep(c(1,1.2,1.5,2),16))
rr_thresh <- as.factor(rep(c(1,1.2,1.5,2),16))
ror_thresh <- as.factor(rep(c(1,1.2,1.5,2),16))
```

```{r sensitivity_plots}
#sensitivity plots
#confidence thresholds
mean_sens_conf <- c(as.numeric(conf_results_beta1[1,]), as.numeric(conf_results_beta10[1,]), as.numeric(conf_results_beta50[1,]), as.numeric(conf_results_beta100[1,]), as.numeric(conf_results_beta1_dep_0_3[1,]), as.numeric(conf_results_beta10_dep_0_3[1,]), as.numeric(conf_results_beta50_dep_0_3[1,]), as.numeric(conf_results_beta100_dep_0_3[1,]), as.numeric(conf_results_beta1_dep_0_5[1,]), as.numeric(conf_results_beta10_dep_0_5[1,]), as.numeric(conf_results_beta50_dep_0_5[1,]), as.numeric(conf_results_beta100_dep_0_5[1,]), as.numeric(conf_results_beta1_dep_0_7[1,]), as.numeric(conf_results_beta10_dep_0_7[1,]), as.numeric(conf_results_beta50_dep_0_7[1,]), as.numeric(conf_results_beta100_dep_0_7[1,]))

#prr thresholds
mean_sens_prr <- c(as.numeric(prr_results_beta1[1,]), as.numeric(prr_results_beta10[1,]), as.numeric(prr_results_beta50[1,]), as.numeric(prr_results_beta100[1,]), as.numeric(prr_results_beta1_dep_0_3[1,]), as.numeric(prr_results_beta10_dep_0_3[1,]), as.numeric(prr_results_beta50_dep_0_3[1,]), as.numeric(prr_results_beta100_dep_0_3[1,]), as.numeric(prr_results_beta1_dep_0_5[1,]), as.numeric(prr_results_beta10_dep_0_5[1,]), as.numeric(prr_results_beta50_dep_0_5[1,]), as.numeric(prr_results_beta100_dep_0_5[1,]), as.numeric(prr_results_beta1_dep_0_7[1,]), as.numeric(prr_results_beta10_dep_0_7[1,]), as.numeric(prr_results_beta50_dep_0_7[1,]), as.numeric(prr_results_beta100_dep_0_7[1,]))

#rr thresholds
mean_sens_rr <- c(as.numeric(rr_results_beta1[1,]), as.numeric(rr_results_beta10[1,]), as.numeric(rr_results_beta50[1,]), as.numeric(rr_results_beta100[1,]), as.numeric(rr_results_beta1_dep_0_3[1,]), as.numeric(rr_results_beta10_dep_0_3[1,]), as.numeric(rr_results_beta50_dep_0_3[1,]), as.numeric(rr_results_beta100_dep_0_3[1,]), as.numeric(rr_results_beta1_dep_0_5[1,]), as.numeric(rr_results_beta10_dep_0_5[1,]), as.numeric(rr_results_beta50_dep_0_5[1,]), as.numeric(rr_results_beta100_dep_0_5[1,]), as.numeric(rr_results_beta1_dep_0_7[1,]), as.numeric(rr_results_beta10_dep_0_7[1,]), as.numeric(rr_results_beta50_dep_0_7[1,]), as.numeric(rr_results_beta100_dep_0_7[1,]))

#ror thresholds
mean_sens_ror <- c(as.numeric(ror_results_beta1[1,]), as.numeric(ror_results_beta10[1,]), as.numeric(ror_results_beta50[1,]), as.numeric(ror_results_beta100[1,]), as.numeric(ror_results_beta1_dep_0_3[1,]), as.numeric(ror_results_beta10_dep_0_3[1,]), as.numeric(ror_results_beta50_dep_0_3[1,]), as.numeric(ror_results_beta100_dep_0_3[1,]), as.numeric(ror_results_beta1_dep_0_5[1,]), as.numeric(ror_results_beta10_dep_0_5[1,]), as.numeric(ror_results_beta50_dep_0_5[1,]), as.numeric(ror_results_beta100_dep_0_5[1,]), as.numeric(ror_results_beta1_dep_0_7[1,]), as.numeric(ror_results_beta10_dep_0_7[1,]), as.numeric(ror_results_beta50_dep_0_7[1,]), as.numeric(ror_results_beta100_dep_0_7[1,]))

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_sens_conf, linetype=betas, color=betas, group=interaction(betas, corr, alpha=0.5))) + 
  geom_point(aes(x=conf_thresh, y=mean_sens_conf, shape=corr, color=betas, group=interaction(betas, corr), alpha=0.5)) + 
  labs(y="Mean Sensitivity", x="Confidence thresholds") +
  theme(legend.position = "none")

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_sens_prr, linetype=betas, color=betas, group=interaction(betas, corr), alpha=0.5)) + 
  geom_point(aes(x=prr_thresh, y=mean_sens_prr, shape=corr, color=betas, group=interaction(betas, corr), alpha=0.5)) +
  labs(y="Mean Sensitivity", x="PRR thresholds") +
  theme(legend.position = "none")

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_sens_rr, linetype=betas, color=betas, group=interaction(betas, corr), alpha=0.5)) + 
  geom_point(aes(x=rr_thresh, y=mean_sens_rr, shape=corr, color=betas, group=interaction(betas, corr), alpha=0.5)) +
  labs(y="Mean Sensitivity", x="RR thresholds") +
  theme(legend.position = "none")

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_sens_ror, linetype=betas, color=betas, group=interaction(betas, corr), alpha=0.5)) + 
  geom_point(aes(x=ror_thresh, y=mean_sens_ror, shape=corr, color=betas, group=interaction(betas, corr), alpha=0.5)) +
  labs(y="Mean Sensitivity", x="ROR thresholds") +
  theme(legend.position = "none")

combined_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2)

g1_legend <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_sens_conf, linetype=betas, color=betas, group=interaction(betas, corr))) + 
  geom_point(aes(x=conf_thresh, y=mean_sens_conf, shape=corr, color=betas, group=interaction(betas, corr))) + 
  labs(y="Mean Sensitivity", x="Confidence thresholds") + 
  scale_color_discrete(name=greeks("beta")) +
  scale_shape_discrete(name=greeks("rho")) +
  scale_linetype_discrete(name=greeks("beta")) +
  theme(legend.position = "bottom")

#function to extract legend from plot
get_only_legend <- function(plot) {
  plot_table <- ggplot_gtable(ggplot_build(plot))
  legend_plot <- which(sapply(plot_table$grobs, function(x) x$name) == "guide-box")
  legend <- plot_table$grobs[[legend_plot]]
  return(legend)
}

#extract legend from g1 using above function
legend <- get_only_legend(g1_legend)

#final combined plot with common legend
grid.arrange(combined_plot, legend, nrow=2, heights=c(10,1), top = "Sensitivity plots for p = 0.1 setting")
```

```{r specificity_plots}
#specificity plots
#confidence thresholds
mean_spec_conf <- c(as.numeric(conf_results_beta1[2,]), as.numeric(conf_results_beta10[2,]), as.numeric(conf_results_beta50[2,]), as.numeric(conf_results_beta100[2,]))

#prr thresholds
mean_spec_prr <- c(as.numeric(prr_results_beta1[2,]), as.numeric(prr_results_beta10[2,]), as.numeric(prr_results_beta50[2,]), as.numeric(prr_results_beta100[2,]))

#rr thresholds
mean_spec_rr <- c(as.numeric(rr_results_beta1[2,]), as.numeric(rr_results_beta10[2,]), as.numeric(rr_results_beta50[2,]), as.numeric(rr_results_beta100[2,]))

#ror thresholds
mean_spec_ror <- c(as.numeric(ror_results_beta1[2,]), as.numeric(ror_results_beta10[2,]), as.numeric(ror_results_beta50[2,]), as.numeric(ror_results_beta100[2,]))

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_spec_conf, linetype=betas, color=betas, group=betas)) + 
  geom_point(aes(x=conf_thresh, y=mean_spec_conf, color=betas, group=betas)) +
  labs(y="Mean Specificity", x="Confidence thresholds", fill = "Beta values") +
  theme(legend.position = "none")

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_spec_prr, linetype=betas, color=betas, group=betas)) + 
  geom_point(aes(x=prr_thresh, y=mean_spec_prr, color=betas, group=betas)) + 
  labs(y="Mean Specificity", x="PRR thresholds", fill = "Beta values") +
  theme(legend.position = "none")

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_spec_rr, linetype=betas, color=betas, group=betas)) +
  geom_point(aes(x=rr_thresh, y=mean_spec_rr, color=betas, group=betas)) +
  labs(y="Mean Specificity", x="RR thresholds", fill = "Beta values") +
  theme(legend.position = "none")

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_spec_ror, linetype=betas, color=betas, group=betas)) + 
  geom_point(aes(x=ror_thresh, y=mean_spec_ror, color=betas, group=betas)) + 
  labs(y="Mean Specificity", x="ROR thresholds", fill = "Beta values") +
  theme(legend.position = "none")

combined_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2)

g1_legend <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_spec_conf, linetype=betas, color=betas, group=betas)) + 
  geom_point(aes(x=conf_thresh, y=mean_spec_conf, color=betas, group=betas)) +
  labs(y="Mean Specificity", x="Confidence thresholds", fill = "Beta values") + 
  theme(legend.position = "bottom")

#extract legend from g1 using above function
legend <- get_only_legend(g1_legend)

#final combined plot with common legend
grid.arrange(combined_plot, legend, nrow=2, heights=c(10,1), top = "Specificity plots for p = 0.1 setting")
```

```{r ppv_plots}
#ppv plots
#confidence thresholds
mean_ppv_conf <- c(as.numeric(conf_results_beta1[3,]), as.numeric(conf_results_beta10[3,]), as.numeric(conf_results_beta50[3,]), as.numeric(conf_results_beta100[3,]))

#prr thresholds
mean_ppv_prr <- c(as.numeric(prr_results_beta1[3,]), as.numeric(prr_results_beta10[3,]), as.numeric(prr_results_beta50[3,]), as.numeric(prr_results_beta100[3,]))

#rr thresholds
mean_ppv_rr <- c(as.numeric(rr_results_beta1[3,]), as.numeric(rr_results_beta10[3,]), as.numeric(rr_results_beta50[3,]), as.numeric(rr_results_beta100[3,]))

#ror thresholds
mean_ppv_ror <- c(as.numeric(ror_results_beta1[3,]), as.numeric(ror_results_beta10[3,]), as.numeric(ror_results_beta50[3,]), as.numeric(ror_results_beta100[3,]))

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_ppv_conf, linetype=betas, color=betas, group=betas)) +
  geom_point(aes(x=conf_thresh, y=mean_ppv_conf, color=betas, group=betas)) +
  labs(y="Mean PPV", x="Confidence thresholds", fill = "Beta values") +
  theme(legend.position = "none")

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_ppv_prr, linetype=betas, color=betas, group=betas)) + 
  geom_point(aes(x=prr_thresh, y=mean_ppv_prr, color=betas, group=betas)) + 
  labs(y="Mean PPV", x="PRR thresholds", fill = "Beta values") +
  theme(legend.position = "none")

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_ppv_rr, linetype=betas, color=betas, group=betas)) +
  geom_point(aes(x=rr_thresh, y=mean_ppv_rr, color=betas, group=betas)) +
  labs(y="Mean PPV", x="RR thresholds", fill = "Beta values") +
  theme(legend.position = "none")

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_ppv_ror, linetype=betas, color=betas, group=betas)) +
  geom_point(aes(x=ror_thresh, y=mean_ppv_ror, color=betas, group=betas)) +
  labs(y="Mean PPV", x="ROR thresholds", fill = "Beta values") +
  theme(legend.position = "none")

combined_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2)

g1_legend <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_ppv_conf, linetype=betas, color=betas, group=betas)) +
  geom_point(aes(x=conf_thresh, y=mean_ppv_conf, color=betas, group=betas)) +
  labs(y="Mean PPV", x="Confidence thresholds", fill = "Beta values") + 
  theme(legend.position = "bottom")

#extract legend from g1 using above function
legend <- get_only_legend(g1_legend)

#final combined plot with common legend
grid.arrange(combined_plot, legend, nrow=2, heights=c(10,1), top = "PPV plots for p = 0.1 setting")
```

```{r npv_plots}
#npv plots
#confidence thresholds
mean_npv_conf <- c(as.numeric(conf_results_beta1[4,]), as.numeric(conf_results_beta10[4,]), as.numeric(conf_results_beta50[4,]), as.numeric(conf_results_beta100[4,]))

#prr thresholds
mean_npv_prr <- c(as.numeric(prr_results_beta1[4,]), as.numeric(prr_results_beta10[4,]), as.numeric(prr_results_beta50[4,]), as.numeric(prr_results_beta100[4,]))

#rr thresholds
mean_npv_rr <- c(as.numeric(rr_results_beta1[4,]), as.numeric(rr_results_beta10[4,]), as.numeric(rr_results_beta50[4,]), as.numeric(rr_results_beta100[4,]))

#ror thresholds
mean_npv_ror <- c(as.numeric(ror_results_beta1[4,]), as.numeric(ror_results_beta10[4,]), as.numeric(ror_results_beta50[4,]), as.numeric(ror_results_beta100[4,]))

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_npv_conf, linetype=betas, color=betas, group=betas)) +
  geom_point(aes(x=conf_thresh, y=mean_npv_conf, color=betas, group=betas)) +
  labs(y="Mean NPV", x="Confidence thresholds", fill = "Beta values") +
  theme(legend.position = "none")

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_npv_prr, linetype=betas, color=betas, group=betas)) + 
  geom_point(aes(x=prr_thresh, y=mean_npv_prr, color=betas, group=betas)) + 
  labs(y="Mean NPV", x="PRR thresholds", fill = "Beta values") +
  theme(legend.position = "none")

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_npv_rr, linetype=betas, color=betas, group=betas)) +
  geom_point(aes(x=rr_thresh, y=mean_npv_rr, color=betas, group=betas)) +
  labs(y="Mean NPV", x="RR thresholds", fill = "Beta values") +
  theme(legend.position = "none")

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_npv_ror, linetype=betas, color=betas, group=betas)) +
  geom_point(aes(x=ror_thresh, y=mean_npv_ror, color=betas, group=betas)) +
  labs(y="Mean NPV", x="ROR thresholds", fill = "Beta values") +
  theme(legend.position = "none")

combined_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2)

g1_legend <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_npv_conf, linetype=betas, color=betas, group=betas)) + 
  geom_point(aes(x=conf_thresh, y=mean_npv_conf, color=betas, group=betas)) + 
  labs(y="Mean NPV", x="Confidence thresholds", fill = "Beta values") + 
  theme(legend.position = "bottom")

#extract legend from g1 using above function
legend <- get_only_legend(g1_legend)

#final combined plot with common legend
grid.arrange(combined_plot, legend, nrow=2, heights=c(10,1), top = "NPV plots for p = 0.1 setting")
```

```{r fscore_plots}
#fscore plots
#confidence thresholds
mean_fscore_conf <- c(as.numeric(conf_results_beta1[5,]), as.numeric(conf_results_beta10[5,]), as.numeric(conf_results_beta50[5,]), as.numeric(conf_results_beta100[5,]))

#prr thresholds
mean_fscore_prr <- c(as.numeric(prr_results_beta1[5,]), as.numeric(prr_results_beta10[5,]), as.numeric(prr_results_beta50[5,]), as.numeric(prr_results_beta100[5,]))

#rr thresholds
mean_fscore_rr <- c(as.numeric(rr_results_beta1[5,]), as.numeric(rr_results_beta10[5,]), as.numeric(rr_results_beta50[5,]), as.numeric(rr_results_beta100[5,]))

#ror thresholds
mean_fscore_ror <- c(as.numeric(ror_results_beta1[5,]), as.numeric(ror_results_beta10[5,]), as.numeric(ror_results_beta50[5,]), as.numeric(ror_results_beta100[5,]))

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_fscore_conf, linetype=betas, color=betas, group=betas)) + 
  geom_point(aes(x=conf_thresh, y=mean_fscore_conf, color=betas, group=betas)) + 
  labs(y="Mean F-score", x="Confidence thresholds", fill = "Beta values") +
  theme(legend.position = "none")

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_fscore_prr, linetype=betas, color=betas, group=betas)) + 
  geom_point(aes(x=prr_thresh, y=mean_fscore_prr, color=betas, group=betas)) + 
  labs(y="Mean F-score", x="PRR thresholds", fill = "Beta values") +
  theme(legend.position = "none")

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_fscore_rr, linetype=betas, color=betas, group=betas)) + 
  geom_point(aes(x=rr_thresh, y=mean_fscore_rr, color=betas, group=betas)) + 
  labs(y="Mean F-score", x="RR thresholds", fill = "Beta values") +
  theme(legend.position = "none")

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_fscore_ror, linetype=betas, color=betas, group=betas)) +
  geom_point(aes(x=ror_thresh, y=mean_fscore_ror, color=betas, group=betas)) +
  labs(y="Mean F-score", x="ROR thresholds", fill = "Beta values") +
  theme(legend.position = "none")

combined_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2)

g1_legend <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_fscore_conf, linetype=betas, color=betas, group=betas)) +
  geom_point(aes(x=conf_thresh, y=mean_fscore_conf, color=betas, group=betas)) +
  labs(y="Mean F-score", x="Confidence thresholds", fill = "Beta values") + 
  theme(legend.position = "bottom")

#extract legend from g1 using above function
legend <- get_only_legend(g1_legend)

#final combined plot with common legend
grid.arrange(combined_plot, legend, nrow=2, heights=c(10,1), top = "F-score plots for p = 0.1 setting")
```