---
title: "Plots for accuracy measures for important pairs in 3 drugs and 5 AEs, p=0.1"
author: "Reetika Sarkar"
output: html_document
---

```{r load_libraries}
## dependent SETTING 1: p=0.1
## impt pairs: d1-ae1, d1-ae2
#plots for accuracy measures

library(ggplot2)
library(gridExtra)
library(ggpubr)
library(greekLetters)
library(repr)
```

```{r read_results_data}
#read file from drive
results_loc_beta1 <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/results/naive_setting_3d_5ae/p_0_1/beta_1"
results_loc_beta10 <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/results/naive_setting_3d_5ae/p_0_1/beta_10"
results_loc_beta50 <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/results/naive_setting_3d_5ae/p_0_1/beta_50"
results_loc_beta100 <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/results/naive_setting_3d_5ae/p_0_1/beta_100"

results_loc_beta1_dep_0_3 <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/results/correlated_setting_3d_5ae/p_0_1/cor_0_3/beta_1/model_2"
results_loc_beta10_dep_0_3 <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/results/correlated_setting_3d_5ae/p_0_1/cor_0_3/beta_10/model_2"
results_loc_beta50_dep_0_3 <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/results/correlated_setting_3d_5ae/p_0_1/cor_0_3/beta_50/model_2"
results_loc_beta100_dep_0_3 <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/results/correlated_setting_3d_5ae/p_0_1/cor_0_3/beta_100/model_2"

results_loc_beta1_dep_neg0_3 <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/results/correlated_setting_3d_5ae/p_0_1/cor_0_3/beta_1/model_3"
results_loc_beta10_dep_neg0_3 <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/results/correlated_setting_3d_5ae/p_0_1/cor_0_3/beta_10/model_3"
results_loc_beta50_dep_neg0_3 <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/results/correlated_setting_3d_5ae/p_0_1/cor_0_3/beta_50/model_3"
results_loc_beta100_dep_neg0_3 <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/results/correlated_setting_3d_5ae/p_0_1/cor_0_3/beta_100/model_3"

results_loc_beta1_dep_0_5 <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/results/correlated_setting_3d_5ae/p_0_1/cor_0_5/beta_1/model_2"
results_loc_beta10_dep_0_5 <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/results/correlated_setting_3d_5ae/p_0_1/cor_0_5/beta_10/model_2"
results_loc_beta50_dep_0_5 <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/results/correlated_setting_3d_5ae/p_0_1/cor_0_5/beta_50/model_2"
results_loc_beta100_dep_0_5 <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/results/correlated_setting_3d_5ae/p_0_1/cor_0_5/beta_100/model_2"

results_loc_beta1_dep_neg0_5 <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/results/correlated_setting_3d_5ae/p_0_1/cor_0_5/beta_1/model_3"
results_loc_beta10_dep_neg0_5 <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/results/correlated_setting_3d_5ae/p_0_1/cor_0_5/beta_10/model_3"
results_loc_beta50_dep_neg0_5 <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/results/correlated_setting_3d_5ae/p_0_1/cor_0_5/beta_50/model_3"
results_loc_beta100_dep_neg0_5 <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/results/correlated_setting_3d_5ae/p_0_1/cor_0_5/beta_100/model_3"

results_loc_beta1_dep_0_7 <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/results/correlated_setting_3d_5ae/p_0_1/cor_0_7/beta_1/model_2"
results_loc_beta10_dep_0_7 <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/results/correlated_setting_3d_5ae/p_0_1/cor_0_7/beta_10/model_2"
results_loc_beta50_dep_0_7 <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/results/correlated_setting_3d_5ae/p_0_1/cor_0_7/beta_50/model_2"
results_loc_beta100_dep_0_7 <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/results/correlated_setting_3d_5ae/p_0_1/cor_0_7/beta_100/model_2"

results_loc_beta1_dep_neg0_7 <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/results/correlated_setting_3d_5ae/p_0_1/cor_0_7/beta_1/model_3"
results_loc_beta10_dep_neg0_7 <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/results/correlated_setting_3d_5ae/p_0_1/cor_0_7/beta_10/model_3"
results_loc_beta50_dep_neg0_7 <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/results/correlated_setting_3d_5ae/p_0_1/cor_0_7/beta_50/model_3"
results_loc_beta100_dep_neg0_7 <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/apriori_project/codes/results/correlated_setting_3d_5ae/p_0_1/cor_0_7/beta_100/model_3"
```

```{r read_sens_values_pair1}
#read sens values for each beta 
# independent setting
conf_results_beta1_pair1 <- read.table(paste0(results_loc_beta1,"/sens_ind_pair_d1a1.csv"), header = T)
conf_results_beta10_pair1 <- read.table(paste0(results_loc_beta10,"/sens_ind_pair_d1a1.csv"), header = T)
conf_results_beta50_pair1 <- read.table(paste0(results_loc_beta50,"/sens_ind_pair_d1a1.csv"), header = T)
conf_results_beta100_pair1 <- read.table(paste0(results_loc_beta100,"/sens_ind_pair_d1a1.csv"), header = T)

# dependent, cor = 0.3
conf_results_beta1_dep_0_3_pair1 <- read.table(paste0(results_loc_beta1_dep_0_3,"/sens_ind_pair_d1a1.csv"), header = T)
conf_results_beta10_dep_0_3_pair1 <- read.table(paste0(results_loc_beta10_dep_0_3,"/sens_ind_pair_d1a1.csv"), header = T)
conf_results_beta50_dep_0_3_pair1 <- read.table(paste0(results_loc_beta50_dep_0_3,"/sens_ind_pair_d1a1.csv"), header = T)
conf_results_beta100_dep_0_3_pair1 <- read.table(paste0(results_loc_beta100_dep_0_3,"/sens_ind_pair_d1a1.csv"), header = T)

# dependent, cor = -0.3
conf_results_beta1_dep_neg0_3_pair1 <- read.table(paste0(results_loc_beta1_dep_neg0_3,"/sens_ind_pair_d1a1.csv"), header = T)
conf_results_beta10_dep_neg0_3_pair1 <- read.table(paste0(results_loc_beta10_dep_neg0_3,"/sens_ind_pair_d1a1.csv"), header = T)
conf_results_beta50_dep_neg0_3_pair1 <- read.table(paste0(results_loc_beta50_dep_neg0_3,"/sens_ind_pair_d1a1.csv"), header = T)
conf_results_beta100_dep_neg0_3_pair1 <- read.table(paste0(results_loc_beta100_dep_neg0_3,"/sens_ind_pair_d1a1.csv"), header = T)

# dependent, cor = 0.5
conf_results_beta1_dep_0_5_pair1 <- read.table(paste0(results_loc_beta1_dep_0_5,"/sens_ind_pair_d1a1.csv"), header = T)
conf_results_beta10_dep_0_5_pair1 <- read.table(paste0(results_loc_beta10_dep_0_5,"/sens_ind_pair_d1a1.csv"), header = T)
conf_results_beta50_dep_0_5_pair1 <- read.table(paste0(results_loc_beta50_dep_0_5,"/sens_ind_pair_d1a1.csv"), header = T)
conf_results_beta100_dep_0_5_pair1 <- read.table(paste0(results_loc_beta100_dep_0_5,"/sens_ind_pair_d1a1.csv"), header = T)

# dependent, cor = -0.5
conf_results_beta1_dep_neg0_5_pair1 <- read.table(paste0(results_loc_beta1_dep_neg0_5,"/sens_ind_pair_d1a1.csv"), header = T)
conf_results_beta10_dep_neg0_5_pair1 <- read.table(paste0(results_loc_beta10_dep_neg0_5,"/sens_ind_pair_d1a1.csv"), header = T)
conf_results_beta50_dep_neg0_5_pair1 <- read.table(paste0(results_loc_beta50_dep_neg0_5,"/sens_ind_pair_d1a1.csv"), header = T)
conf_results_beta100_dep_neg0_5_pair1 <- read.table(paste0(results_loc_beta100_dep_neg0_5,"/sens_ind_pair_d1a1.csv"), header = T)

# dependent, cor = 0.7
conf_results_beta1_dep_0_7_pair1 <- read.table(paste0(results_loc_beta1_dep_0_7,"/sens_ind_pair_d1a1.csv"), header = T)
conf_results_beta10_dep_0_7_pair1 <- read.table(paste0(results_loc_beta10_dep_0_7,"/sens_ind_pair_d1a1.csv"), header = T)
conf_results_beta50_dep_0_7_pair1 <- read.table(paste0(results_loc_beta50_dep_0_7,"/sens_ind_pair_d1a1.csv"), header = T)
conf_results_beta100_dep_0_7_pair1 <- read.table(paste0(results_loc_beta100_dep_0_7,"/sens_ind_pair_d1a1.csv"), header = T)

# dependent, cor = -0.7
conf_results_beta1_dep_neg0_7_pair1 <- read.table(paste0(results_loc_beta1_dep_neg0_7,"/sens_ind_pair_d1a1.csv"), header = T)
conf_results_beta10_dep_neg0_7_pair1 <- read.table(paste0(results_loc_beta10_dep_neg0_7,"/sens_ind_pair_d1a1.csv"), header = T)
conf_results_beta50_dep_neg0_7_pair1 <- read.table(paste0(results_loc_beta50_dep_neg0_7,"/sens_ind_pair_d1a1.csv"), header = T)
conf_results_beta100_dep_neg0_7_pair1 <- read.table(paste0(results_loc_beta100_dep_neg0_7,"/sens_ind_pair_d1a1.csv"), header = T)
```

```{r read_sens_values_pair2}
#read sens values for each beta 
# independent setting
conf_results_beta1_pair2 <- read.table(paste0(results_loc_beta1,"/sens_ind_pair_d1a2.csv"), header = T)
conf_results_beta10_pair2 <- read.table(paste0(results_loc_beta10,"/sens_ind_pair_d1a2.csv"), header = T)
conf_results_beta50_pair2 <- read.table(paste0(results_loc_beta50,"/sens_ind_pair_d1a2.csv"), header = T)
conf_results_beta100_pair2 <- read.table(paste0(results_loc_beta100,"/sens_ind_pair_d1a2.csv"), header = T)

# dependent, cor = 0.3
conf_results_beta1_dep_0_3_pair2 <- read.table(paste0(results_loc_beta1_dep_0_3,"/sens_ind_pair_d1a2.csv"), header = T)
conf_results_beta10_dep_0_3_pair2 <- read.table(paste0(results_loc_beta10_dep_0_3,"/sens_ind_pair_d1a2.csv"), header = T)
conf_results_beta50_dep_0_3_pair2 <- read.table(paste0(results_loc_beta50_dep_0_3,"/sens_ind_pair_d1a2.csv"), header = T)
conf_results_beta100_dep_0_3_pair2 <- read.table(paste0(results_loc_beta100_dep_0_3,"/sens_ind_pair_d1a2.csv"), header = T)

# dependent, cor = -0.3
conf_results_beta1_dep_neg0_3_pair2 <- read.table(paste0(results_loc_beta1_dep_neg0_3,"/sens_ind_pair_d1a2.csv"), header = T)
conf_results_beta10_dep_neg0_3_pair2 <- read.table(paste0(results_loc_beta10_dep_neg0_3,"/sens_ind_pair_d1a2.csv"), header = T)
conf_results_beta50_dep_neg0_3_pair2 <- read.table(paste0(results_loc_beta50_dep_neg0_3,"/sens_ind_pair_d1a2.csv"), header = T)
conf_results_beta100_dep_neg0_3_pair2 <- read.table(paste0(results_loc_beta100_dep_neg0_3,"/sens_ind_pair_d1a2.csv"), header = T)

# dependent, cor = 0.5
conf_results_beta1_dep_0_5_pair2 <- read.table(paste0(results_loc_beta1_dep_0_5,"/sens_ind_pair_d1a2.csv"), header = T)
conf_results_beta10_dep_0_5_pair2 <- read.table(paste0(results_loc_beta10_dep_0_5,"/sens_ind_pair_d1a2.csv"), header = T)
conf_results_beta50_dep_0_5_pair2 <- read.table(paste0(results_loc_beta50_dep_0_5,"/sens_ind_pair_d1a2.csv"), header = T)
conf_results_beta100_dep_0_5_pair2 <- read.table(paste0(results_loc_beta100_dep_0_5,"/sens_ind_pair_d1a2.csv"), header = T)

# dependent, cor = -0.5
conf_results_beta1_dep_neg0_5_pair2 <- read.table(paste0(results_loc_beta1_dep_neg0_5,"/sens_ind_pair_d1a2.csv"), header = T)
conf_results_beta10_dep_neg0_5_pair2 <- read.table(paste0(results_loc_beta10_dep_neg0_5,"/sens_ind_pair_d1a2.csv"), header = T)
conf_results_beta50_dep_neg0_5_pair2 <- read.table(paste0(results_loc_beta50_dep_neg0_5,"/sens_ind_pair_d1a2.csv"), header = T)
conf_results_beta100_dep_neg0_5_pair2 <- read.table(paste0(results_loc_beta100_dep_neg0_5,"/sens_ind_pair_d1a2.csv"), header = T)

# dependent, cor = 0.7
conf_results_beta1_dep_0_7_pair2 <- read.table(paste0(results_loc_beta1_dep_0_7,"/sens_ind_pair_d1a2.csv"), header = T)
conf_results_beta10_dep_0_7_pair2 <- read.table(paste0(results_loc_beta10_dep_0_7,"/sens_ind_pair_d1a2.csv"), header = T)
conf_results_beta50_dep_0_7_pair2 <- read.table(paste0(results_loc_beta50_dep_0_7,"/sens_ind_pair_d1a2.csv"), header = T)
conf_results_beta100_dep_0_7_pair2 <- read.table(paste0(results_loc_beta100_dep_0_7,"/sens_ind_pair_d1a2.csv"), header = T)

# dependent, cor = -0.7
conf_results_beta1_dep_neg0_7_pair2 <- read.table(paste0(results_loc_beta1_dep_neg0_7,"/sens_ind_pair_d1a2.csv"), header = T)
conf_results_beta10_dep_neg0_7_pair2 <- read.table(paste0(results_loc_beta10_dep_neg0_7,"/sens_ind_pair_d1a2.csv"), header = T)
conf_results_beta50_dep_neg0_7_pair2 <- read.table(paste0(results_loc_beta50_dep_neg0_7,"/sens_ind_pair_d1a2.csv"), header = T)
conf_results_beta100_dep_neg0_7_pair2 <- read.table(paste0(results_loc_beta100_dep_neg0_7,"/sens_ind_pair_d1a2.csv"), header = T)
```

```{r define_thresholds}
betas <- as.factor(rep(c(rep(1,4), rep(10,4), rep(50,4), rep(100,4)), 7))
corr <- as.factor(c(rep(0, 16), rep(0.3, 16), rep(-0.3, 16), rep(0.5, 16), rep(-0.5, 16), rep(0.7, 16), rep(-0.7, 16)))
conf_thresh <- as.factor(rep(c(0.4,0.5,0.6,0.7), 28))
prr_thresh <- as.factor(rep(c(1,1.2,1.5,2), 28))
rr_thresh <- as.factor(rep(c(1,1.2,1.5,2), 28))
ror_thresh <- as.factor(rep(c(1,1.2,1.5,2), 28))
```

```{r sensitivity_plots_pair1}
#sensitivity plots for d1-ae1
#confidence thresholds
mean_sens_conf_pair1 <- c(as.numeric(conf_results_beta1_pair1[1,]), as.numeric(conf_results_beta10_pair1[1,]), as.numeric(conf_results_beta50_pair1[1,]), as.numeric(conf_results_beta100_pair1[1,]), as.numeric(conf_results_beta1_dep_0_3_pair1[1,]), as.numeric(conf_results_beta10_dep_0_3_pair1[1,]), as.numeric(conf_results_beta50_dep_0_3_pair1[1,]), as.numeric(conf_results_beta100_dep_0_3_pair1[1,]), as.numeric(conf_results_beta1_dep_neg0_3_pair1[1,]), as.numeric(conf_results_beta10_dep_neg0_3_pair1[1,]), as.numeric(conf_results_beta50_dep_neg0_3_pair1[1,]), as.numeric(conf_results_beta100_dep_neg0_3_pair1[1,]), as.numeric(conf_results_beta1_dep_0_5_pair1[1,]), as.numeric(conf_results_beta10_dep_0_5_pair1[1,]),  as.numeric(conf_results_beta50_dep_0_5_pair1[1,]), as.numeric(conf_results_beta100_dep_0_5_pair1[1,]), as.numeric(conf_results_beta1_dep_neg0_5_pair1[1,]), as.numeric(conf_results_beta10_dep_neg0_5_pair1[1,]),  as.numeric(conf_results_beta50_dep_neg0_5_pair1[1,]), as.numeric(conf_results_beta100_dep_neg0_5_pair1[1,]), as.numeric(conf_results_beta1_dep_0_7_pair1[1,]), as.numeric(conf_results_beta10_dep_0_7_pair1[1,]), as.numeric(conf_results_beta50_dep_0_7_pair1[1,]), as.numeric(conf_results_beta100_dep_0_7_pair1[1,]), as.numeric(conf_results_beta1_dep_neg0_7_pair1[1,]), as.numeric(conf_results_beta10_dep_neg0_7_pair1[1,]), as.numeric(conf_results_beta50_dep_neg0_7_pair1[1,]), as.numeric(conf_results_beta100_dep_neg0_7_pair1[1,]))

#prr thresholds
mean_sens_prr_pair1 <- c(as.numeric(conf_results_beta1_pair1[2,]), as.numeric(conf_results_beta10_pair1[2,]), as.numeric(conf_results_beta50_pair1[2,]), as.numeric(conf_results_beta100_pair1[2,]), as.numeric(conf_results_beta1_dep_0_3_pair1[2,]), as.numeric(conf_results_beta10_dep_0_3_pair1[2,]), as.numeric(conf_results_beta50_dep_0_3_pair1[2,]), as.numeric(conf_results_beta100_dep_0_3_pair1[2,]), as.numeric(conf_results_beta1_dep_neg0_3_pair1[2,]), as.numeric(conf_results_beta10_dep_neg0_3_pair1[2,]), as.numeric(conf_results_beta50_dep_neg0_3_pair1[2,]), as.numeric(conf_results_beta100_dep_neg0_3_pair1[2,]), as.numeric(conf_results_beta1_dep_0_5_pair1[2,]), as.numeric(conf_results_beta10_dep_0_5_pair1[2,]),  as.numeric(conf_results_beta50_dep_0_5_pair1[2,]), as.numeric(conf_results_beta100_dep_0_5_pair1[2,]), as.numeric(conf_results_beta1_dep_neg0_5_pair1[2,]), as.numeric(conf_results_beta10_dep_neg0_5_pair1[2,]),  as.numeric(conf_results_beta50_dep_neg0_5_pair1[2,]), as.numeric(conf_results_beta100_dep_neg0_5_pair1[2,]), as.numeric(conf_results_beta1_dep_0_7_pair1[2,]), as.numeric(conf_results_beta10_dep_0_7_pair1[2,]), as.numeric(conf_results_beta50_dep_0_7_pair1[2,]), as.numeric(conf_results_beta100_dep_0_7_pair1[2,]), as.numeric(conf_results_beta1_dep_neg0_7_pair1[2,]), as.numeric(conf_results_beta10_dep_neg0_7_pair1[2,]), as.numeric(conf_results_beta50_dep_neg0_7_pair1[2,]), as.numeric(conf_results_beta100_dep_neg0_7_pair1[2,]))

#rr thresholds
mean_sens_rr_pair1 <- c(as.numeric(conf_results_beta1_pair1[3,]), as.numeric(conf_results_beta10_pair1[3,]), as.numeric(conf_results_beta50_pair1[3,]), as.numeric(conf_results_beta100_pair1[3,]), as.numeric(conf_results_beta1_dep_0_3_pair1[3,]), as.numeric(conf_results_beta10_dep_0_3_pair1[3,]), as.numeric(conf_results_beta50_dep_0_3_pair1[3,]), as.numeric(conf_results_beta100_dep_0_3_pair1[3,]), as.numeric(conf_results_beta1_dep_neg0_3_pair1[3,]), as.numeric(conf_results_beta10_dep_neg0_3_pair1[3,]), as.numeric(conf_results_beta50_dep_neg0_3_pair1[3,]), as.numeric(conf_results_beta100_dep_neg0_3_pair1[3,]), as.numeric(conf_results_beta1_dep_0_5_pair1[3,]), as.numeric(conf_results_beta10_dep_0_5_pair1[3,]),  as.numeric(conf_results_beta50_dep_0_5_pair1[3,]), as.numeric(conf_results_beta100_dep_0_5_pair1[3,]), as.numeric(conf_results_beta1_dep_neg0_5_pair1[3,]), as.numeric(conf_results_beta10_dep_neg0_5_pair1[3,]),  as.numeric(conf_results_beta50_dep_neg0_5_pair1[3,]), as.numeric(conf_results_beta100_dep_neg0_5_pair1[3,]), as.numeric(conf_results_beta1_dep_0_7_pair1[3,]), as.numeric(conf_results_beta10_dep_0_7_pair1[3,]), as.numeric(conf_results_beta50_dep_0_7_pair1[3,]), as.numeric(conf_results_beta100_dep_0_7_pair1[3,]), as.numeric(conf_results_beta1_dep_neg0_7_pair1[3,]), as.numeric(conf_results_beta10_dep_neg0_7_pair1[3,]), as.numeric(conf_results_beta50_dep_neg0_7_pair1[3,]), as.numeric(conf_results_beta100_dep_neg0_7_pair1[3,]))

#ror thresholds
mean_sens_ror_pair1 <- c(as.numeric(conf_results_beta1_pair1[4,]), as.numeric(conf_results_beta10_pair1[4,]), as.numeric(conf_results_beta50_pair1[4,]), as.numeric(conf_results_beta100_pair1[4,]), as.numeric(conf_results_beta1_dep_0_3_pair1[4,]), as.numeric(conf_results_beta10_dep_0_3_pair1[4,]), as.numeric(conf_results_beta50_dep_0_3_pair1[4,]), as.numeric(conf_results_beta100_dep_0_3_pair1[4,]), as.numeric(conf_results_beta1_dep_neg0_3_pair1[4,]), as.numeric(conf_results_beta10_dep_neg0_3_pair1[4,]), as.numeric(conf_results_beta50_dep_neg0_3_pair1[4,]), as.numeric(conf_results_beta100_dep_neg0_3_pair1[4,]), as.numeric(conf_results_beta1_dep_0_5_pair1[4,]), as.numeric(conf_results_beta10_dep_0_5_pair1[4,]),  as.numeric(conf_results_beta50_dep_0_5_pair1[4,]), as.numeric(conf_results_beta100_dep_0_5_pair1[4,]), as.numeric(conf_results_beta1_dep_neg0_5_pair1[4,]), as.numeric(conf_results_beta10_dep_neg0_5_pair1[4,]),  as.numeric(conf_results_beta50_dep_neg0_5_pair1[4,]), as.numeric(conf_results_beta100_dep_neg0_5_pair1[4,]), as.numeric(conf_results_beta1_dep_0_7_pair1[4,]), as.numeric(conf_results_beta10_dep_0_7_pair1[4,]), as.numeric(conf_results_beta50_dep_0_7_pair1[4,]), as.numeric(conf_results_beta100_dep_0_7_pair1[4,]), as.numeric(conf_results_beta1_dep_neg0_7_pair1[4,]), as.numeric(conf_results_beta10_dep_neg0_7_pair1[4,]), as.numeric(conf_results_beta50_dep_neg0_7_pair1[4,]), as.numeric(conf_results_beta100_dep_neg0_7_pair1[4,]))

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_sens_conf_pair1, linetype=betas, color=corr, group=interaction(betas, corr), alpha=0.8)) +
  geom_point(aes(x=conf_thresh, y=mean_sens_conf_pair1, shape=betas, color=corr, group=interaction(betas, corr), alpha=0.8)) + 
  ylim(0,1) +
  scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#33a02c","#fb9a99","#e31a1c","#fdbf6f")) +
  labs(y="Mean Sensitivity", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_sens_prr_pair1, linetype=betas, color=corr, group=interaction(betas, corr), alpha=0.8)) + 
  geom_point(aes(x=prr_thresh, y=mean_sens_prr_pair1, shape=betas, color=corr, group=interaction(betas, corr), alpha=0.8)) +
  ylim(0,1) +
  scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#33a02c","#fb9a99","#e31a1c","#fdbf6f")) +
  labs(y="Mean Sensitivity", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_sens_rr_pair1, color=corr, linetype=betas, group=interaction(betas, corr), alpha=0.8)) + 
  geom_point(aes(x=rr_thresh, y=mean_sens_rr_pair1, shape=betas, color=corr, group=interaction(betas, corr), alpha=0.8)) +
  ylim(0,1) +
  scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#33a02c","#fb9a99","#e31a1c","#fdbf6f")) +
  labs(y="Mean Sensitivity", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))
g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_sens_ror_pair1, color=corr, linetype=betas, group=interaction(betas, corr), alpha=0.8)) + 
  geom_point(aes(x=ror_thresh, y=mean_sens_ror_pair1, shape=betas, color=corr, group=interaction(betas, corr), alpha=0.8)) +
  ylim(0,1) +
  scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#33a02c","#fb9a99","#e31a1c","#fdbf6f")) +
  labs(y="Mean Sensitivity", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2)

g1_legend <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_sens_conf_pair1, linetype=betas, color=corr, group=interaction(betas, corr))) + 
  geom_point(aes(x=conf_thresh, y=mean_sens_conf_pair1, shape=betas, color=corr, group=interaction(betas, corr))) + 
  ylim(0,1) +
  scale_shape_manual(values = c(15,16,17,18), name=greeks("beta")) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#33a02c","#fb9a99","#e31a1c","#fdbf6f"), name=greeks("rho")) +
  labs(y="Mean Sensitivity", x="Confidence thresholds") + 
  #scale_color_discrete(name=greeks("rho")) +
  #scale_shape_discrete(name=greeks("beta")) +
  scale_linetype_discrete(name=greeks("beta")) +
  theme(legend.position = "bottom", axis.text=element_text(size=10),
        axis.title=element_text(size=8), legend.title = element_text(size=10, face="bold"), 
        legend.text = element_text(size=8))

#function to extract legend from plot
get_only_legend <- function(plot) {
  plot_table <- ggplot_gtable(ggplot_build(plot))
  legend_plot <- which(sapply(plot_table$grobs, function(x) x$name) == "guide-box")
  legend <- plot_table$grobs[[legend_plot]]
  return(legend)
}

#extract legend from g1 using above function
legend <- get_only_legend(g1_legend)

#final combined plot with common legend
combined_sens_plot_pair1 <- grid.arrange(combined_plot, legend, nrow=2, heights=c(8.5,2), top = "Sensitivity plots for drug1-AE1 pair, 3 drugs and 5 AEs (p = 0.1) setting")
sens_plot_file_pair1 <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/codes/plots/setting_3d_5ae/p_0_1/sens_pair1.png"
#print(combined_sens_plot)
ggsave(filename = sens_plot_file_pair1, plot = combined_sens_plot_pair1)
```

```{r sensitivity_plots_pair2}
#sensitivity plots for d1-ae2
#confidence thresholds
mean_sens_conf_pair2 <- c(as.numeric(conf_results_beta1_pair2[1,]), as.numeric(conf_results_beta10_pair2[1,]), as.numeric(conf_results_beta50_pair2[1,]), as.numeric(conf_results_beta100_pair2[1,]), as.numeric(conf_results_beta1_dep_0_3_pair2[1,]), as.numeric(conf_results_beta10_dep_0_3_pair2[1,]), as.numeric(conf_results_beta50_dep_0_3_pair2[1,]), as.numeric(conf_results_beta100_dep_0_3_pair2[1,]), as.numeric(conf_results_beta1_dep_neg0_3_pair2[1,]), as.numeric(conf_results_beta10_dep_neg0_3_pair2[1,]), as.numeric(conf_results_beta50_dep_neg0_3_pair2[1,]), as.numeric(conf_results_beta100_dep_neg0_3_pair2[1,]), as.numeric(conf_results_beta1_dep_0_5_pair2[1,]), as.numeric(conf_results_beta10_dep_0_5_pair2[1,]),  as.numeric(conf_results_beta50_dep_0_5_pair2[1,]), as.numeric(conf_results_beta100_dep_0_5_pair2[1,]), as.numeric(conf_results_beta1_dep_neg0_5_pair2[1,]), as.numeric(conf_results_beta10_dep_neg0_5_pair2[1,]),  as.numeric(conf_results_beta50_dep_neg0_5_pair2[1,]), as.numeric(conf_results_beta100_dep_neg0_5_pair2[1,]), as.numeric(conf_results_beta1_dep_0_7_pair2[1,]), as.numeric(conf_results_beta10_dep_0_7_pair2[1,]), as.numeric(conf_results_beta50_dep_0_7_pair2[1,]), as.numeric(conf_results_beta100_dep_0_7_pair2[1,]), as.numeric(conf_results_beta1_dep_neg0_7_pair2[1,]), as.numeric(conf_results_beta10_dep_neg0_7_pair2[1,]), as.numeric(conf_results_beta50_dep_neg0_7_pair2[1,]), as.numeric(conf_results_beta100_dep_neg0_7_pair2[1,]))

#prr thresholds
mean_sens_prr_pair2 <- c(as.numeric(conf_results_beta1_pair2[2,]), as.numeric(conf_results_beta10_pair2[2,]), as.numeric(conf_results_beta50_pair2[2,]), as.numeric(conf_results_beta100_pair2[2,]), as.numeric(conf_results_beta1_dep_0_3_pair2[2,]), as.numeric(conf_results_beta10_dep_0_3_pair2[2,]), as.numeric(conf_results_beta50_dep_0_3_pair2[2,]), as.numeric(conf_results_beta100_dep_0_3_pair2[2,]), as.numeric(conf_results_beta1_dep_neg0_3_pair2[2,]), as.numeric(conf_results_beta10_dep_neg0_3_pair2[2,]), as.numeric(conf_results_beta50_dep_neg0_3_pair2[2,]), as.numeric(conf_results_beta100_dep_neg0_3_pair2[2,]), as.numeric(conf_results_beta1_dep_0_5_pair2[2,]), as.numeric(conf_results_beta10_dep_0_5_pair2[2,]),  as.numeric(conf_results_beta50_dep_0_5_pair2[2,]), as.numeric(conf_results_beta100_dep_0_5_pair2[2,]), as.numeric(conf_results_beta1_dep_neg0_5_pair2[2,]), as.numeric(conf_results_beta10_dep_neg0_5_pair2[2,]),  as.numeric(conf_results_beta50_dep_neg0_5_pair2[2,]), as.numeric(conf_results_beta100_dep_neg0_5_pair2[2,]), as.numeric(conf_results_beta1_dep_0_7_pair2[2,]), as.numeric(conf_results_beta10_dep_0_7_pair2[2,]), as.numeric(conf_results_beta50_dep_0_7_pair2[2,]), as.numeric(conf_results_beta100_dep_0_7_pair2[2,]), as.numeric(conf_results_beta1_dep_neg0_7_pair2[2,]), as.numeric(conf_results_beta10_dep_neg0_7_pair2[2,]), as.numeric(conf_results_beta50_dep_neg0_7_pair2[2,]), as.numeric(conf_results_beta100_dep_neg0_7_pair2[2,]))

#rr thresholds
mean_sens_rr_pair2 <- c(as.numeric(conf_results_beta1_pair2[3,]), as.numeric(conf_results_beta10_pair2[3,]), as.numeric(conf_results_beta50_pair2[3,]), as.numeric(conf_results_beta100_pair2[3,]), as.numeric(conf_results_beta1_dep_0_3_pair2[3,]), as.numeric(conf_results_beta10_dep_0_3_pair2[3,]), as.numeric(conf_results_beta50_dep_0_3_pair2[3,]), as.numeric(conf_results_beta100_dep_0_3_pair2[3,]), as.numeric(conf_results_beta1_dep_neg0_3_pair2[3,]), as.numeric(conf_results_beta10_dep_neg0_3_pair2[3,]), as.numeric(conf_results_beta50_dep_neg0_3_pair2[3,]), as.numeric(conf_results_beta100_dep_neg0_3_pair2[3,]), as.numeric(conf_results_beta1_dep_0_5_pair2[3,]), as.numeric(conf_results_beta10_dep_0_5_pair2[3,]),  as.numeric(conf_results_beta50_dep_0_5_pair2[3,]), as.numeric(conf_results_beta100_dep_0_5_pair2[3,]), as.numeric(conf_results_beta1_dep_neg0_5_pair2[3,]), as.numeric(conf_results_beta10_dep_neg0_5_pair2[3,]),  as.numeric(conf_results_beta50_dep_neg0_5_pair2[3,]), as.numeric(conf_results_beta100_dep_neg0_5_pair2[3,]), as.numeric(conf_results_beta1_dep_0_7_pair2[3,]), as.numeric(conf_results_beta10_dep_0_7_pair2[3,]), as.numeric(conf_results_beta50_dep_0_7_pair2[3,]), as.numeric(conf_results_beta100_dep_0_7_pair2[3,]), as.numeric(conf_results_beta1_dep_neg0_7_pair2[3,]), as.numeric(conf_results_beta10_dep_neg0_7_pair2[3,]), as.numeric(conf_results_beta50_dep_neg0_7_pair2[3,]), as.numeric(conf_results_beta100_dep_neg0_7_pair2[3,]))

#ror thresholds
mean_sens_ror_pair2 <- c(as.numeric(conf_results_beta1_pair2[4,]), as.numeric(conf_results_beta10_pair2[4,]), as.numeric(conf_results_beta50_pair2[4,]), as.numeric(conf_results_beta100_pair2[4,]), as.numeric(conf_results_beta1_dep_0_3_pair2[4,]), as.numeric(conf_results_beta10_dep_0_3_pair2[4,]), as.numeric(conf_results_beta50_dep_0_3_pair2[4,]), as.numeric(conf_results_beta100_dep_0_3_pair2[4,]), as.numeric(conf_results_beta1_dep_neg0_3_pair2[4,]), as.numeric(conf_results_beta10_dep_neg0_3_pair2[4,]), as.numeric(conf_results_beta50_dep_neg0_3_pair2[4,]), as.numeric(conf_results_beta100_dep_neg0_3_pair2[4,]), as.numeric(conf_results_beta1_dep_0_5_pair2[4,]), as.numeric(conf_results_beta10_dep_0_5_pair2[4,]),  as.numeric(conf_results_beta50_dep_0_5_pair2[4,]), as.numeric(conf_results_beta100_dep_0_5_pair2[4,]), as.numeric(conf_results_beta1_dep_neg0_5_pair2[4,]), as.numeric(conf_results_beta10_dep_neg0_5_pair2[4,]),  as.numeric(conf_results_beta50_dep_neg0_5_pair2[4,]), as.numeric(conf_results_beta100_dep_neg0_5_pair2[4,]), as.numeric(conf_results_beta1_dep_0_7_pair2[4,]), as.numeric(conf_results_beta10_dep_0_7_pair2[4,]), as.numeric(conf_results_beta50_dep_0_7_pair2[4,]), as.numeric(conf_results_beta100_dep_0_7_pair2[4,]), as.numeric(conf_results_beta1_dep_neg0_7_pair2[4,]), as.numeric(conf_results_beta10_dep_neg0_7_pair2[4,]), as.numeric(conf_results_beta50_dep_neg0_7_pair2[4,]), as.numeric(conf_results_beta100_dep_neg0_7_pair2[4,]))

g1 <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_sens_conf_pair2, linetype=betas, color=corr, group=interaction(betas, corr), alpha=0.8)) +
  geom_point(aes(x=conf_thresh, y=mean_sens_conf_pair2, shape=betas, color=corr, group=interaction(betas, corr), alpha=0.8)) + 
  ylim(0,1) +
  scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#33a02c","#fb9a99","#e31a1c","#fdbf6f")) +
  labs(y="Mean Sensitivity", x="Confidence thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g2 <- ggplot() + 
  geom_line(aes(x=prr_thresh, y=mean_sens_prr_pair2, linetype=betas, color=corr, group=interaction(betas, corr), alpha=0.8)) + 
  geom_point(aes(x=prr_thresh, y=mean_sens_prr_pair2, shape=betas, color=corr, group=interaction(betas, corr), alpha=0.8)) +
  ylim(0,1) +
  scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#33a02c","#fb9a99","#e31a1c","#fdbf6f")) +
  labs(y="Mean Sensitivity", x="PRR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g3 <- ggplot() + 
  geom_line(aes(x=rr_thresh, y=mean_sens_rr_pair2, color=corr, linetype=betas, group=interaction(betas, corr), alpha=0.8)) + 
  geom_point(aes(x=rr_thresh, y=mean_sens_rr_pair2, shape=betas, color=corr, group=interaction(betas, corr), alpha=0.8)) +
  ylim(0,1) +
  scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#33a02c","#fb9a99","#e31a1c","#fdbf6f")) +
  labs(y="Mean Sensitivity", x="RR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

g4 <- ggplot() + 
  geom_line(aes(x=ror_thresh, y=mean_sens_ror_pair2, color=corr, linetype=betas, group=interaction(betas, corr), alpha=0.8)) + 
  geom_point(aes(x=ror_thresh, y=mean_sens_ror_pair2, shape=betas, color=corr, group=interaction(betas, corr), alpha=0.8)) +
  ylim(0,1) +
  scale_shape_manual(values = c(15,16,17,18)) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#33a02c","#fb9a99","#e31a1c","#fdbf6f")) +
  labs(y="Mean Sensitivity", x="ROR thresholds") +
  theme(legend.position = "none", axis.text=element_text(size=8),
        axis.title=element_text(size=8))

combined_plot <- grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2)

g1_legend <- ggplot() + 
  geom_line(aes(x=conf_thresh, y=mean_sens_conf_pair2, linetype=betas, color=corr, group=interaction(betas, corr))) + 
  geom_point(aes(x=conf_thresh, y=mean_sens_conf_pair2, shape=betas, color=corr, group=interaction(betas, corr))) + 
  ylim(0,1) +
  scale_shape_manual(values = c(15,16,17,18), name=greeks("beta")) +
  scale_color_manual(values = c("#a6cee3","#1f78b4","#b2df8a","#33a02c","#fb9a99","#e31a1c","#fdbf6f"), name=greeks("rho")) +
  labs(y="Mean Sensitivity", x="Confidence thresholds") + 
  #scale_color_discrete(name=greeks("rho")) +
  #scale_shape_discrete(name=greeks("beta")) +
  scale_linetype_discrete(name=greeks("beta")) +
  theme(legend.position = "bottom", axis.text=element_text(size=10),
        axis.title=element_text(size=8), legend.title = element_text(size=10, face="bold"), 
        legend.text = element_text(size=8))

#function to extract legend from plot
get_only_legend <- function(plot) {
  plot_table <- ggplot_gtable(ggplot_build(plot))
  legend_plot <- which(sapply(plot_table$grobs, function(x) x$name) == "guide-box")
  legend <- plot_table$grobs[[legend_plot]]
  return(legend)
}

#extract legend from g1 using above function
legend <- get_only_legend(g1_legend)

#final combined plot with common legend
combined_sens_plot_pair2 <- grid.arrange(combined_plot, legend, nrow=2, heights=c(8.5,2), top = "Sensitivity plots for drug1-AE2 pair, 3 drugs and 5 AEs (p = 0.1) setting")
sens_plot_file_pair2 <- "/Users/reetikasarkar/Dropbox/My Mac (Reetika’s MacBook Pro)/Documents/dissertation_research/codes/plots/setting_3d_5ae/p_0_1/sens_pair2.png"
#print(combined_sens_plot)
ggsave(filename = sens_plot_file_pair2, plot = combined_sens_plot_pair2)
```

